Repository mesosphere/charts, pull requests merged in 2019-07, with the labels that each got.

#5 localvolumeprovisioner: single storageclass with flag for default
  stable/localvolumeprovisioner/Chart.yaml
  stable/localvolumeprovisioner/templates/NOTES.txt
  stable/localvolumeprovisioner/templates/deployment.yaml
  stable/localvolumeprovisioner/templates/storageclass.yaml
  stable/localvolumeprovisioner/values.yaml
Labels: ready

#11 charts/staging: add dex-k8s-authenticator repository
  staging/dex-k8s-authenticator/.helmignore
  staging/dex-k8s-authenticator/Chart.yaml
  staging/dex-k8s-authenticator/LICENSE
  staging/dex-k8s-authenticator/README.md
  staging/dex-k8s-authenticator/out.yaml
  staging/dex-k8s-authenticator/templates/NOTES.txt
  staging/dex-k8s-authenticator/templates/_helpers.tpl
  staging/dex-k8s-authenticator/templates/ca_secrets.yaml
  staging/dex-k8s-authenticator/templates/configmap.yaml
  staging/dex-k8s-authenticator/templates/deployment.yaml
  staging/dex-k8s-authenticator/templates/ingress.yaml
  staging/dex-k8s-authenticator/templates/service.yaml
  staging/dex-k8s-authenticator/values.yaml
Labels: ready

#10 Makefile: publish to fork
  Makefile
Labels: ready

#17 Makefile: pull latest changes and rebase using our changes
  Makefile
Labels: ready

#15 charts: add kommander
  stable/kommander/Chart.yaml
  stable/kommander/templates/crd.yaml
  stable/kommander/templates/deployment.yaml
  stable/kommander/templates/service.yaml
  stable/kommander/templates/serviceaccount.yaml
  stable/kommander/values.yaml
Labels: ready

#19 Makefile: restore and fix old remote
  Makefile
Labels: bug

#14 updates to provisioner chart
  stable/localvolumeprovisioner/Chart.yaml
  stable/localvolumeprovisioner/templates/configmap.yaml
  stable/localvolumeprovisioner/templates/daemonset.yaml
  stable/localvolumeprovisioner/templates/deployment.yaml
  stable/localvolumeprovisioner/templates/roles.yaml
  stable/localvolumeprovisioner/values.yaml
Labels: ready

#20 attempting to fix make publish
  Makefile
Labels: ready

#23 Makefile: fix publish issue
  Makefile
Labels: bug, ready

#22 Use Release.namespace to pass the namespace name to kommander
  stable/kommander/Chart.yaml
  stable/kommander/templates/deployment.yaml
  stable/kommander/templates/service.yaml
  stable/kommander/templates/serviceaccount.yaml
Labels: ready

#24 dex-k8s-authenticator: add custom templates
  staging/dex-k8s-authenticator/Chart.yaml
  staging/dex-k8s-authenticator/html-templates/index.html
  staging/dex-k8s-authenticator/html-templates/kubeconfig.html
  staging/dex-k8s-authenticator/html-templates/linux-mac-common.html
  staging/dex-k8s-authenticator/html-templates/linux-tab.html
  staging/dex-k8s-authenticator/html-templates/mac-tab.html
  staging/dex-k8s-authenticator/html-templates/windows-tab.html
  staging/dex-k8s-authenticator/templates/ca_secrets.yaml
  staging/dex-k8s-authenticator/templates/configmap.yaml
  staging/dex-k8s-authenticator/templates/configmap_templates.yaml
  staging/dex-k8s-authenticator/templates/deployment.yaml
  staging/dex-k8s-authenticator/templates/ingress.yaml
  staging/dex-k8s-authenticator/templates/service.yaml
Labels: p1, ready

#25 fix: wrong reference to variable in the template
  stable/kommander/templates/deployment.yaml
Labels: bug, ready

#16 Add traefik-forward-auth chart
  staging/traefik-forward-auth/.helmignore
  staging/traefik-forward-auth/Chart.yaml
  staging/traefik-forward-auth/LICENSE
  staging/traefik-forward-auth/README.md
  staging/traefik-forward-auth/templates/NOTES.txt
  staging/traefik-forward-auth/templates/_helpers.tpl
  staging/traefik-forward-auth/templates/configmap.yaml
  staging/traefik-forward-auth/templates/deployment.yaml
  staging/traefik-forward-auth/templates/ingress.yaml
  staging/traefik-forward-auth/templates/secret.yaml
  staging/traefik-forward-auth/templates/service.yaml
  staging/traefik-forward-auth/templates/tests/test-connection.yaml
  staging/traefik-forward-auth/values.yaml
Labels: p1, ready

#27 opsportal chart
  stable/opsportal/Chart.yaml
  stable/opsportal/html-templates/index.html
  stable/opsportal/templates/configmap-landing.yaml
  stable/opsportal/templates/deployment-bearerproxy.yaml
  stable/opsportal/templates/deployment-landing.yaml
  stable/opsportal/templates/ingress-landing.yaml
  stable/opsportal/templates/ingress-opsportal.yaml
  stable/opsportal/templates/roles-bearerproxy.yaml
  stable/opsportal/templates/service-bearerproxy.yaml
  stable/opsportal/templates/service-landing.yaml
  stable/opsportal/values.yaml
Labels: ready

#28 dex-k8s-authenticator: set timeouts to readiness and liveness probes
  staging/dex-k8s-authenticator/templates/deployment.yaml
  staging/dex-k8s-authenticator/values.yaml
Labels: bug, ready

#26 awsebscsiprovisioner chart updated
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/README.md
  stable/awsebscsiprovisioner/templates/_helpers.tpl
  stable/awsebscsiprovisioner/templates/daemonset.yaml
  stable/awsebscsiprovisioner/templates/deployment.yaml
  stable/awsebscsiprovisioner/templates/roles.yaml
  stable/awsebscsiprovisioner/templates/secrets.yaml
  stable/awsebscsiprovisioner/templates/statefulset.yaml
  stable/awsebscsiprovisioner/values.yaml
Labels: ready

#30 Add ingress to kommander
  stable/kommander/Chart.yaml
  stable/kommander/templates/_helpers.tpl
  stable/kommander/templates/crd.yaml
  stable/kommander/templates/deployment.yaml
  stable/kommander/templates/ingress.yaml
  stable/kommander/templates/service.yaml
  stable/kommander/templates/serviceaccount.yaml
  stable/kommander/values.yaml
Labels: p1

#32 staging: temporary add traefik
  staging/traefik/Chart.yaml
  staging/traefik/OWNERS
  staging/traefik/README.md
  staging/traefik/templates/NOTES.txt
  staging/traefik/templates/_helpers.tpl
  staging/traefik/templates/acme-pvc.yaml
  staging/traefik/templates/config-files.yaml
  staging/traefik/templates/configmap.yaml
  staging/traefik/templates/dashboard-ingress.yaml
  staging/traefik/templates/dashboard-service.yaml
  staging/traefik/templates/default-cert-secret.yaml
  staging/traefik/templates/deployment.yaml
  staging/traefik/templates/dns-provider-secret.yaml
  staging/traefik/templates/hpa.yaml
  staging/traefik/templates/poddisruptionbudget.yaml
  staging/traefik/templates/rbac.yaml
  staging/traefik/templates/secret-files.yaml
  staging/traefik/templates/service.yaml
  staging/traefik/templates/storeconfig-job.yaml
  staging/traefik/templates/tests/test-configmap.yaml
  staging/traefik/templates/tests/test.yaml
  staging/traefik/values.yaml
Labels: ready

#34 Add initContainers to traefik-forward-auth chart
  staging/traefik-forward-auth/Chart.yaml
  staging/traefik-forward-auth/templates/deployment.yaml
  staging/traefik-forward-auth/values.yaml
Labels: ready

#35 Add temporary placeholder for traefik-forward-auth
  staging/traefik-forward-auth/templates/secret.yaml
Labels: ready

#33 stable: add X-Forwarded-User to opsportal and kommander
  stable/kommander/Chart.yaml
  stable/kommander/templates/ingress.yaml
  stable/kommander/values.yaml
  stable/opsportal/Chart.yaml
Labels: ready

#37 Ae/provisioiner/fixes
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/templates/daemonset.yaml
  stable/awsebscsiprovisioner/templates/statefulset.yaml
  stable/awsebscsiprovisioner/values.yaml
Labels: ready

#39 fixing selector matchlabels and template name lable to match
  stable/kommander/Chart.yaml
  stable/kommander/templates/deployment.yaml
Labels: ready

#40 stable/dex: add dex chart with initContainers support
  stable/dex/.helmignore
  stable/dex/Chart.yaml
  stable/dex/OWNERS
  stable/dex/config/openssl.conf
  stable/dex/templates/NOTES.txt
  stable/dex/templates/_helpers.tpl
  stable/dex/templates/clusterrole.yaml
  stable/dex/templates/clusterrolebinding.yaml
  stable/dex/templates/config-openssl.yaml
  stable/dex/templates/deployment.yaml
  stable/dex/templates/ingress.yaml
  stable/dex/templates/job-grpc-certs.yaml
  stable/dex/templates/job-web-certs.yaml
  stable/dex/templates/poddisruptionbudget.yaml
  stable/dex/templates/role.yaml
  stable/dex/templates/rolebinding.yaml
  stable/dex/templates/secret.yaml
  stable/dex/templates/service.yaml
  stable/dex/templates/serviceaccount.yaml
  stable/dex/values.yaml
Labels: ready

#44 should not deploy ops-portal-secret
  staging/traefik-forward-auth/Chart.yaml
  staging/traefik-forward-auth/templates/configmap.yaml
  staging/traefik-forward-auth/templates/secret.yaml
Labels: ready

#48 Fix SA name for EBS CSI chart
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/templates/roles.yaml
Labels: ready

#47 update kommander and opsportal charts
  stable/kommander/Chart.yaml
  stable/kommander/templates/crd.yaml
  stable/kommander/templates/deployment.yaml
  stable/kommander/templates/ingress.yaml
  stable/kommander/templates/observablecluster.yaml
  stable/kommander/templates/serviceaccount.yaml
  stable/kommander/values.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/html-templates/index.html
  stable/opsportal/templates/_helperts.tpl
  stable/opsportal/templates/configmap-landing.yaml
  stable/opsportal/templates/deployment-bearerproxy.yaml
  stable/opsportal/templates/deployment-landing.yaml
  stable/opsportal/templates/ingress-landing.yaml
  stable/opsportal/templates/ingress-opsportal.yaml
  stable/opsportal/templates/roles-bearerproxy.yaml
  stable/opsportal/templates/service-bearerproxy.yaml
  stable/opsportal/templates/service-landing.yaml
  stable/opsportal/values.yaml
Labels: ready

#46 Update kommander to 1.45.0
  stable/kommander/Chart.yaml
  stable/kommander/templates/deployment.yaml
  stable/kommander/values.yaml
Labels: ready

#49 bump kommander image and simplify mode
  stable/kommander/Chart.yaml
  stable/kommander/templates/deployment.yaml
  stable/kommander/values.yaml
Labels: ready

#51 Enable secretmanagement for dex initcontainers
  stable/dex/Chart.yaml
  stable/dex/templates/role.yaml
  stable/dex/templates/rolebinding.yaml
Labels: ready

#50 install ct if not installed
  Makefile
  test/ct.yaml
Labels: ready

#52 landing for ops portal and Traefik config
  stable/kommander/Chart.yaml
  stable/kommander/templates/ingress.yaml
  stable/kommander/values.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/templates/ingress-opsportal.yaml
  stable/opsportal/templates/landing.yaml
  stable/opsportal/values.yaml
Labels: ready

#53 kommander: add conditional to install the CRD
  stable/kommander/Chart.yaml
  stable/kommander/templates/crd.yaml
  stable/kommander/values.yaml
Labels: ready

#54 fix: remove logo and brand link
  stable/opsportal/Chart.yaml
  stable/opsportal/templates/landing.yaml
Labels: ready

#58 fix: change logout redirect to '/landing' in kommander
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: ready

#60 dex-k8s-authenticator: avoid using subPath for the secret
  staging/dex-k8s-authenticator/Chart.yaml
  staging/dex-k8s-authenticator/templates/deployment.yaml
  staging/dex-k8s-authenticator/values.yaml
Labels: ready

#61 Add service monitor label to kommander
  stable/kommander/Chart.yaml
  stable/kommander/templates/service.yaml
Labels: ready

#64 Add staging/velero with Minio backend support
  staging/velero/.helmignore
  staging/velero/Chart.yaml
  staging/velero/OWNERS
  staging/velero/README.md
  staging/velero/ci/test-values.yaml
  staging/velero/templates/NOTES.txt
  staging/velero/templates/_helpers.tpl
  staging/velero/templates/backups.yaml
  staging/velero/templates/backupstoragelocation.yaml
  staging/velero/templates/backupstoragelocations.yaml
  staging/velero/templates/cleanup-crds.yaml
  staging/velero/templates/configmaps.yaml
  staging/velero/templates/deletebackuprequests.yaml
  staging/velero/templates/deployment.yaml
  staging/velero/templates/downloadrequests.yaml
  staging/velero/templates/miniobackend.yaml
  staging/velero/templates/podvolumebackups.yaml
  staging/velero/templates/podvolumerestores.yaml
  staging/velero/templates/rbac.yaml
  staging/velero/templates/restic-daemonset.yaml
  staging/velero/templates/resticrepositories.yaml
  staging/velero/templates/restores.yaml
  staging/velero/templates/schedule.yaml
  staging/velero/templates/schedules.yaml
  staging/velero/templates/secret.yaml
  staging/velero/templates/serverstatusrequests.yaml
  staging/velero/templates/service.yaml
  staging/velero/templates/serviceaccount-server.yaml
  staging/velero/templates/servicemonitor.yaml
  staging/velero/templates/volumesnapshotlocation.yaml
  staging/velero/templates/volumesnapshotlocations.yaml
  staging/velero/values.yaml
Labels: ready

#68 Add the ability to view services to dex sa
  stable/dex/Chart.yaml
  stable/dex/templates/role.yaml
Labels: ready

#63 stable/storage charts: set tolerations and critical priority
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/templates/daemonset.yaml
  stable/awsebscsiprovisioner/values.yaml
  stable/localvolumeprovisioner/Chart.yaml
  stable/localvolumeprovisioner/templates/daemonset.yaml
  stable/localvolumeprovisioner/values.yaml
Labels: ready

#72 add optional configuration parameters for AWS EBS volumes.
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/templates/storageclass.yaml
  stable/awsebscsiprovisioner/values.yaml
  stable/awsebsprovisioner/Chart.yaml
  stable/awsebsprovisioner/templates/storageclass.yaml
Labels: ready

#62 dex-k8s-authenticator: stop using subPath in general for dex-k8s-auth
  staging/dex-k8s-authenticator/Chart.yaml
  staging/dex-k8s-authenticator/README.md
  staging/dex-k8s-authenticator/templates/deployment.yaml
Labels: ready

#75 Add dex authenticator init containers
  staging/dex-k8s-authenticator/Chart.yaml
  staging/dex-k8s-authenticator/templates/deployment.yaml
  staging/dex-k8s-authenticator/templates/rbac.yaml
  staging/dex-k8s-authenticator/values.yaml
Labels: ready

#74 tfa: create secret as hooks
  staging/traefik-forward-auth/Chart.yaml
  staging/traefik-forward-auth/templates/deployment.yaml
  staging/traefik-forward-auth/templates/hooks.yaml
  staging/traefik-forward-auth/templates/rolebinding.yaml
  staging/traefik-forward-auth/templates/secret.yaml
  staging/traefik-forward-auth/values.yaml
Labels: ready

#76 Add Konvoy UI dashboard
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/konvoyuidashboard.yaml
  staging/prometheus-operator/values.yaml
Labels: ready

#80 stable/awsebscsiprovisioner: Fix topology support
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/templates/statefulset.yaml
Labels: ready

#78 Use d2iq urls for landing page links
  stable/opsportal/Chart.yaml
  stable/opsportal/templates/landing.yaml
Labels: ready

#81 [extrasteps] opsportal updated with hooks for secrets generation
  stable/opsportal/Chart.yaml
  stable/opsportal/templates/hooks-roles.yaml
  stable/opsportal/templates/hooks-secrets.yaml
  stable/opsportal/values.yaml
Labels: wip

#84 localvolumeprovisioner: allow configuration of multiple storage classes
  stable/localvolumeprovisioner/Chart.yaml
  stable/localvolumeprovisioner/templates/NOTES.txt
  stable/localvolumeprovisioner/templates/configmap.yaml
  stable/localvolumeprovisioner/templates/daemonset.yaml
  stable/localvolumeprovisioner/templates/storageclass.yaml
  stable/localvolumeprovisioner/values.yaml
Labels: ready

#86 awsebscsiprovisioner: set allowed topologies values
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/templates/storageclass.yaml
  stable/awsebscsiprovisioner/values.yaml
Labels: ready

#85 Open landing page links in new tab
  stable/opsportal/Chart.yaml
  stable/opsportal/templates/landing.yaml
Labels: ready

#87 prometheus-operator: typo in the mesosphere resources
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/traefikdashboard.yaml
  staging/prometheus-operator/values.yaml
Labels: bug, ready

#89 Bump kommander image
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: ready

#88 Update ES dashboard and fix syntax error
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/elasticsearchdashboard.yaml
Labels: ready

#65 Added a chart for github eventing source.
  staging/knative/charts/eventing-sources/Chart.yaml
  staging/knative/charts/eventing-sources/charts/github/Chart.yaml
  staging/knative/charts/eventing-sources/charts/github/LICENSE
  staging/knative/charts/eventing-sources/charts/github/templates/clusterrole.yaml
  staging/knative/charts/eventing-sources/charts/github/templates/clusterrolebinding.yaml
  staging/knative/charts/eventing-sources/charts/github/templates/controller-service.yaml
  staging/knative/charts/eventing-sources/charts/github/templates/controller.yaml
  staging/knative/charts/eventing-sources/charts/github/templates/githubsource.yaml
  staging/knative/charts/eventing-sources/charts/github/templates/namespace.yaml
  staging/knative/charts/eventing-sources/charts/github/templates/serviceaccount.yaml
  staging/knative/charts/eventing-sources/charts/github/values.yaml
  staging/knative/charts/eventing-sources/values.yaml
Labels: ready

#90 localvolumeprovisioner: remove hardcoded ns and comment priorityclass
  stable/localvolumeprovisioner/Chart.yaml
  stable/localvolumeprovisioner/templates/configmap.yaml
  stable/localvolumeprovisioner/templates/daemonset.yaml
  stable/localvolumeprovisioner/templates/roles.yaml
  stable/localvolumeprovisioner/templates/service.yaml
Labels: p1, ready

#91 Update charts for new mesosphere/ images
  stable/opsportal/Chart.yaml
  stable/opsportal/values.yaml
  staging/traefik-forward-auth/Chart.yaml
  staging/traefik-forward-auth/templates/hooks.yaml
  staging/velero/Chart.yaml
  staging/velero/templates/deployment.yaml
  staging/velero/templates/miniobackend.yaml
Labels: ready

#92 opsportla: fix image tag
  stable/opsportal/Chart.yaml
  stable/opsportal/values.yaml
Labels: ready

#93 Revert 354e37bda91e18fb3645f88d1ed082794992f47c
  stable/localvolumeprovisioner/Chart.yaml
  stable/localvolumeprovisioner/templates/NOTES.txt
  stable/localvolumeprovisioner/templates/configmap.yaml
  stable/localvolumeprovisioner/templates/daemonset.yaml
  stable/localvolumeprovisioner/templates/storageclass.yaml
  stable/localvolumeprovisioner/values.yaml
Labels: ready

#95 Remove local path provisioner
  stable/localpathprovisioner/Chart.yaml
  stable/localpathprovisioner/templates/deployment.yaml
  stable/localpathprovisioner/templates/storageclass.yaml
  stable/localpathprovisioner/values.yaml
Labels: ready

#94 opsportal: merge konvoy ui in opsportal
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-0.1.21.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
  stable/opsportal/values.yaml
Labels: ready

#96 velero/minio changes
  staging/velero/Chart.yaml
  staging/velero/templates/deployment.yaml
  staging/velero/templates/miniobackend.yaml
  staging/velero/values.yaml
Labels: ready
