Repository mesosphere/charts, pull requests merged in 2019-12, with the labels that each got.

#289 Set catalog address for kommander chart
  stable/kommander/Chart.yaml
  stable/kommander/templates/deployment.yaml
  stable/kommander/values.yaml
Labels: bug, ready

#292 chore: tekton is now its own chart
  stable/tekton/.helmignore
  stable/tekton/Chart.yaml
  stable/tekton/files/crd-clustertask.yaml
  stable/tekton/files/crd-condition.yaml
  stable/tekton/files/crd-image.yaml
  stable/tekton/files/crd-pipeline.yaml
  stable/tekton/files/crd-pipelineresource.yaml
  stable/tekton/files/crd-pipelinerun.yaml
  stable/tekton/files/crd-task.yaml
  stable/tekton/files/crd-taskrun.yaml
  stable/tekton/templates/NOTES.txt
  stable/tekton/templates/_helpers.tpl
  stable/tekton/templates/clusterrolebindings.yaml
  stable/tekton/templates/clusterroles.yaml
  stable/tekton/templates/configmaps.yaml
  stable/tekton/templates/controller-deployment.yaml
  stable/tekton/templates/controller-service.yaml
  stable/tekton/templates/crds.yaml
  stable/tekton/templates/podsecuritypolicies.yaml
  stable/tekton/templates/servicceaccounts.yaml
  stable/tekton/templates/webhook-deployment.yaml
  stable/tekton/templates/webhook-service.yaml
  stable/tekton/values.yaml
Labels: ready

#298 [tekton] fix: tekton sa and webhook name fixed
  stable/tekton/Chart.yaml
  stable/tekton/templates/webhook-deployment.yaml
  stable/tekton/templates/webhook-service.yaml
Labels: ready

#297 [dispatch] chore: add tekton as a requirement, manage crds correctly
  stable/dispatch/Chart.yaml
  stable/dispatch/charts/minio-2.5.14.tgz
  stable/dispatch/charts/minio/.helmignore
  stable/dispatch/charts/minio/Chart.yaml
  stable/dispatch/charts/minio/OWNERS
  stable/dispatch/charts/minio/README.md
  stable/dispatch/charts/minio/ci/distributed-values.yaml
  stable/dispatch/charts/minio/templates/NOTES.txt
  stable/dispatch/charts/minio/templates/_helper_create_bucket.txt
  stable/dispatch/charts/minio/templates/_helpers.tpl
  stable/dispatch/charts/minio/templates/configmap.yaml
  stable/dispatch/charts/minio/templates/deployment.yaml
  stable/dispatch/charts/minio/templates/ingress.yaml
  stable/dispatch/charts/minio/templates/networkpolicy.yaml
  stable/dispatch/charts/minio/templates/post-install-create-bucket-job.yaml
  stable/dispatch/charts/minio/templates/pvc.yaml
  stable/dispatch/charts/minio/templates/secrets.yaml
  stable/dispatch/charts/minio/templates/service.yaml
  stable/dispatch/charts/minio/templates/serviceaccount.yaml
  stable/dispatch/charts/minio/templates/servicemonitor.yaml
  stable/dispatch/charts/minio/templates/statefulset.yaml
  stable/dispatch/charts/minio/values.yaml
  stable/dispatch/charts/tekton-0.1.3.tgz
  stable/dispatch/charts/tekton/.helmignore
  stable/dispatch/charts/tekton/Chart.yaml
  stable/dispatch/charts/tekton/templates/NOTES.txt
  stable/dispatch/charts/tekton/templates/_helpers.tpl
  stable/dispatch/charts/tekton/templates/tekton.yaml
  stable/dispatch/charts/tekton/values.yaml
  stable/dispatch/files/crd-repository.yaml
  stable/dispatch/requirements.lock
  stable/dispatch/requirements.yaml
  stable/dispatch/templates/crds.yaml
  stable/dispatch/templates/dashboard-argocd.yaml
  stable/dispatch/templates/dashboard-cloudbuild.yaml
  stable/dispatch/templates/deployment-event-sink.yaml
  stable/dispatch/templates/deployment-repository-controller.yaml
  stable/dispatch/templates/event-sink.yaml
  stable/dispatch/templates/ingress.yaml
  stable/dispatch/templates/report-status.yaml
  stable/dispatch/templates/repository-controller.yaml
  stable/dispatch/templates/roles-event-sink.yaml
  stable/dispatch/templates/roles-report-status.yaml
  stable/dispatch/templates/roles-repository-controller.yaml
  stable/dispatch/templates/roles-update-image-digests.yaml
  stable/dispatch/templates/secrets.yaml
  stable/dispatch/templates/serviceaccount.yaml
  stable/dispatch/templates/servicemonitor.yaml
  stable/dispatch/templates/services.yaml
  stable/dispatch/templates/task-report-status.yaml
  stable/dispatch/templates/task-update-image-digests.yaml
  stable/dispatch/templates/update-image-digests.yaml
  stable/dispatch/values.yaml
  test/ct.yaml
Labels: ready

#301 [argo-cd] argo-cd chart added
  stable/argo-cd/.helmignore
  stable/argo-cd/Chart.yaml
  stable/argo-cd/LICENSE
  stable/argo-cd/README.md
  stable/argo-cd/files/application-crd.yaml
  stable/argo-cd/files/appproject-crd.yaml
  stable/argo-cd/templates/NOTES.txt
  stable/argo-cd/templates/_helpers.tpl
  stable/argo-cd/templates/argocd-application-controller-clusterrole.yaml
  stable/argo-cd/templates/argocd-application-controller-clusterrolebinding.yaml
  stable/argo-cd/templates/argocd-application-controller-deployment.yaml
  stable/argo-cd/templates/argocd-application-controller-metrics-service.yaml
  stable/argo-cd/templates/argocd-application-controller-metrics-servicemonitor.yaml
  stable/argo-cd/templates/argocd-application-controller-role.yaml
  stable/argo-cd/templates/argocd-application-controller-rolebinding.yaml
  stable/argo-cd/templates/argocd-application-controller-sa.yaml
  stable/argo-cd/templates/argocd-application-controller-service.yaml
  stable/argo-cd/templates/argocd-cm.yaml
  stable/argo-cd/templates/argocd-dex-server-deployment.yaml
  stable/argo-cd/templates/argocd-dex-server-role.yaml
  stable/argo-cd/templates/argocd-dex-server-rolebinding.yaml
  stable/argo-cd/templates/argocd-dex-server-sa.yaml
  stable/argo-cd/templates/argocd-dex-server-service.yaml
  stable/argo-cd/templates/argocd-rbac-cm.yaml
  stable/argo-cd/templates/argocd-redis-deployment.yaml
  stable/argo-cd/templates/argocd-redis-service.yaml
  stable/argo-cd/templates/argocd-repo-server-deployment.yaml
  stable/argo-cd/templates/argocd-repo-server-metrics.yaml
  stable/argo-cd/templates/argocd-repo-server-service.yaml
  stable/argo-cd/templates/argocd-repo-server-servicemonitor.yaml
  stable/argo-cd/templates/argocd-secret.yaml
  stable/argo-cd/templates/argocd-server-certificate.yaml
  stable/argo-cd/templates/argocd-server-clusterrole.yaml
  stable/argo-cd/templates/argocd-server-clusterrolebinding.yaml
  stable/argo-cd/templates/argocd-server-deployment.yaml
  stable/argo-cd/templates/argocd-server-ingress.yaml
  stable/argo-cd/templates/argocd-server-metrics.yaml
  stable/argo-cd/templates/argocd-server-role.yaml
  stable/argo-cd/templates/argocd-server-rolebinding.yaml
  stable/argo-cd/templates/argocd-server-sa.yaml
  stable/argo-cd/templates/argocd-server-service.yaml
  stable/argo-cd/templates/argocd-server-servicemonitor.yaml
  stable/argo-cd/templates/argocd-ssh-known-hosts-cm.yaml
  stable/argo-cd/templates/argocd-tls-certs-cm.yaml
  stable/argo-cd/templates/argocd-webhook-ingress.yaml
  stable/argo-cd/templates/crds.yaml
  stable/argo-cd/values.yaml
Labels: ready

#302 chore: bump KCL to v0.2.5
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.3.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.5.tgz
  stable/kommander/charts/kommander-karma-0.2.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.4.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#299 prometheus-operator: bump kube-state-metrics version
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/charts/grafana-3.5.10.tgz
  staging/prometheus-operator/charts/kube-state-metrics-1.6.5.tgz
  staging/prometheus-operator/charts/kube-state-metrics-2.4.1.tgz
  staging/prometheus-operator/charts/prometheus-node-exporter-1.5.1.tgz
  staging/prometheus-operator/dependent-charts/kube-state-metrics/Chart.yaml
  staging/prometheus-operator/dependent-charts/kube-state-metrics/README.md
  staging/prometheus-operator/dependent-charts/kube-state-metrics/templates/clusterrole.yaml
  staging/prometheus-operator/dependent-charts/kube-state-metrics/templates/clusterrolebinding.yaml
  staging/prometheus-operator/dependent-charts/kube-state-metrics/templates/deployment.yaml
  staging/prometheus-operator/dependent-charts/kube-state-metrics/templates/podsecuritypolicy.yaml
  staging/prometheus-operator/dependent-charts/kube-state-metrics/templates/psp-clusterrole.yaml
  staging/prometheus-operator/dependent-charts/kube-state-metrics/templates/psp-clusterrolebinding.yaml
  staging/prometheus-operator/dependent-charts/kube-state-metrics/templates/service.yaml
  staging/prometheus-operator/dependent-charts/kube-state-metrics/templates/serviceaccount.yaml
  staging/prometheus-operator/dependent-charts/kube-state-metrics/templates/servicemonitor.yaml
  staging/prometheus-operator/dependent-charts/kube-state-metrics/values.yaml
  staging/prometheus-operator/requirements.lock
  staging/prometheus-operator/requirements.yaml
Labels: ready

#304 chore(kommander): bump KCL to v0.2.6
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.5.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.6.tgz
  stable/kommander/charts/kommander-karma-0.2.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.4.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#303 [dispatch] add argo-cd in requirement.yaml
  stable/dispatch/Chart.yaml
  stable/dispatch/charts/argo-cd-0.5.4.tgz
  stable/dispatch/charts/argo-cd/.helmignore
  stable/dispatch/charts/argo-cd/Chart.yaml
  stable/dispatch/charts/argo-cd/LICENSE
  stable/dispatch/charts/argo-cd/README.md
  stable/dispatch/charts/argo-cd/templates/NOTES.txt
  stable/dispatch/charts/argo-cd/templates/_helpers.tpl
  stable/dispatch/charts/argo-cd/templates/argocd-application-controller-clusterrole.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-application-controller-clusterrolebinding.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-application-controller-deployment.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-application-controller-metrics-service.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-application-controller-metrics-servicemonitor.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-application-controller-role.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-application-controller-rolebinding.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-application-controller-sa.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-application-controller-service.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-cm.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-dex-server-deployment.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-dex-server-role.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-dex-server-rolebinding.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-dex-server-sa.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-dex-server-service.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-rbac-cm.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-redis-deployment.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-redis-service.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-repo-server-deployment.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-repo-server-metrics.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-repo-server-service.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-repo-server-servicemonitor.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-secret.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-server-certificate.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-server-clusterrole.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-server-clusterrolebinding.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-server-deployment.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-server-ingress.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-server-metrics.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-server-role.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-server-rolebinding.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-server-sa.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-server-service.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-server-servicemonitor.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-ssh-known-hosts-cm.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-tls-certs-cm.yaml
  stable/dispatch/charts/argo-cd/templates/argocd-webhook-ingress.yaml
  stable/dispatch/charts/argo-cd/templates/crds/application-crd.yaml
  stable/dispatch/charts/argo-cd/templates/crds/appproject-crd.yaml
  stable/dispatch/charts/argo-cd/values.yaml
  stable/dispatch/charts/tekton-0.1.3.tgz
  stable/dispatch/requirements.lock
  stable/dispatch/requirements.yaml
  stable/dispatch/templates/servicemonitor.yaml
  stable/dispatch/values.yaml
Labels: ready

#305 chore(kommander): bump KCL to v0.2.7
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.6.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.7.tgz
  stable/kommander/charts/kommander-karma-0.2.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.4.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#308 Add devx team as CODEOWNERS for stable/dispatch
  CODEOWNERS
Labels: ready

#311 chore: bump kommander/opsportal image to 1.169.0
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/values.yaml
Labels: ready

#285 Added Nvidia GPU monitoring support.
  staging/nvidia/Chart.yaml
  staging/nvidia/charts/grafana/.helmignore
  staging/nvidia/charts/grafana/Chart.yaml
  staging/nvidia/charts/grafana/LICENSE
  staging/nvidia/charts/grafana/templates/_helpers.tpl
  staging/nvidia/charts/grafana/templates/configmap-dashboards.yaml
  staging/nvidia/charts/grafana/values.yaml
  staging/nvidia/charts/nvidia-dcgm-exporter/.helmignore
  staging/nvidia/charts/nvidia-dcgm-exporter/Chart.yaml
  staging/nvidia/charts/nvidia-dcgm-exporter/LICENSE
  staging/nvidia/charts/nvidia-dcgm-exporter/templates/_helpers.tpl
  staging/nvidia/charts/nvidia-dcgm-exporter/templates/daemonset.yaml
  staging/nvidia/charts/nvidia-dcgm-exporter/templates/tests/test-connection.yaml
  staging/nvidia/charts/nvidia-dcgm-exporter/values.yaml
Labels: ready

#313 Use TFA service account for job
  staging/traefik-forward-auth/Chart.yaml
  staging/traefik-forward-auth/templates/clusterrole.yaml
  staging/traefik-forward-auth/templates/hooks.yaml
Labels: ready

#286 kommander-thanos: Bump thanos subchart, add file SD configmaps
  stable/kommander-thanos/Chart.yaml
  stable/kommander-thanos/README.md
  stable/kommander-thanos/charts/thanos-0.3.6.tgz
  stable/kommander-thanos/charts/thanos-0.3.9.tgz
  stable/kommander-thanos/requirements.lock
  stable/kommander-thanos/requirements.yaml
  stable/kommander-thanos/templates/query-stores-configmap.yaml
  stable/kommander-thanos/values.yaml
Labels: ready

#317 Bump dex controller
  stable/dex-controller/README.md
  stable/dex/Chart.yaml
  stable/dex/charts/dex-controller-0.2.1.tgz
  stable/dex/charts/dex-controller-v0.3.0.tgz
  stable/dex/requirements.lock
  stable/dex/requirements.yaml
  test/ct.yaml
Labels: ready

#318 kommander: bump kommander-thanos subchart and kommander
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma-0.2.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.4.tgz
  stable/kommander/charts/kommander-thanos-0.1.5.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
Labels: ready

#320 traefik: add support for custom certificate
  staging/traefik/Chart.yaml
  staging/traefik/templates/configmap.yaml
  staging/traefik/templates/deployment.yaml
  staging/traefik/values.yaml
Labels: ready

#321 kommander-karma: Use upstream karma chart, handle cm during upgrade/uninstall
  stable/kommander-karma/Chart.yaml
  stable/kommander-karma/README.md
  stable/kommander-karma/charts/karma-1.3.0.tgz
  stable/kommander-karma/charts/karma-1.4.0.tgz
  stable/kommander-karma/requirements.lock
  stable/kommander-karma/requirements.yaml
  stable/kommander-karma/templates/cleanup-configmap.yaml
  stable/kommander-karma/values.yaml
  stable/kommander-thanos/Chart.yaml
  stable/kommander-thanos/templates/query-stores-configmap.yaml
  staging/karma/.helmignore
  staging/karma/Chart.yaml
  staging/karma/OWNERS
  staging/karma/README.md
  staging/karma/ci/test-values.yaml
  staging/karma/templates/NOTES.txt
  staging/karma/templates/_helpers.tpl
  staging/karma/templates/configmap.yaml
  staging/karma/templates/deployment.yaml
  staging/karma/templates/ingress.yaml
  staging/karma/templates/service.yaml
  staging/karma/templates/serviceaccount.yaml
  staging/karma/values.yaml
  staging/velero/Chart.yaml
  staging/velero/templates/cleanup-crds.yaml
Labels: ready

#323 chore: bump kcl version
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.7.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.3.1.tgz
  stable/kommander/charts/kommander-karma-0.2.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.5.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: blocked, ready

#325 kommander: update kubeaddonsRepository property name
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: bug, ready

#324 kommander: Bump kommander-karma and kommander-thanos
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma-0.2.0.tgz
  stable/kommander/charts/kommander-karma-0.3.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.5.tgz
  stable/kommander/charts/kommander-thanos-0.1.6.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
Labels: ready

#326 kommander: bump kcl
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.3.1.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.3.2.tgz
  stable/kommander/charts/kommander-karma-0.3.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.6.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready
