Repository mesosphere/charts, pull requests merged in 2019-11, with the labels that each got.

#229 kommander: udpate to version v0.1.10 of kcl
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.1.10.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.1.9.tgz
  stable/kommander/charts/kommander-thanos-0.1.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#217 Add kommander-karma chart
  stable/kommander-karma/.helmignore
  stable/kommander-karma/Chart.yaml
  stable/kommander-karma/README.md
  stable/kommander-karma/charts/karma-1.1.21.tgz
  stable/kommander-karma/requirements.lock
  stable/kommander-karma/requirements.yaml
  stable/kommander-karma/templates/_helpers.tpl
  stable/kommander-karma/templates/federated-addon.yaml
  stable/kommander-karma/templates/secret.yaml
  stable/kommander-karma/values.yaml
Labels: ready

#231 kommander: Add grafana dashboard for Thanos Query
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/dashboards/thanos-query-dashboard.yaml
Labels: ready

#218 kommander: Add Karma
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma-0.1.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
Labels: ready

#233 kommander: enable federated ingress
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: ready

#238 kommander: Update KCL dependency to 0.2.0
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.1.10.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.0.tgz
  stable/kommander/charts/kommander-karma-0.1.1.tgz
  stable/kommander/charts/kommander-thanos-0.1.4.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#237 [kommander] crd fix (part 1)
  stable/kommander/Chart.yaml
  stable/kommander/files/federated-addons.yaml
  stable/kommander/files/federated-cluster-rolebindings.yaml
  stable/kommander/files/federated-clusteraddons.yaml
  stable/kommander/files/federated-customresourcedefinition.yaml
  stable/kommander/files/federated-rolebindings.yaml
  stable/kommander/files/federated-roles.yaml
  stable/kommander/files/observableclusters-crd.yaml
  stable/kommander/templates/federated-crds.yaml
  stable/kommander/templates/federated-kubeaddons.yaml
  stable/kommander/templates/federated-typeconfigs.yaml
  stable/kommander/templates/observable-crd.yaml
Labels: ready

#240 [kommander] chore: remove observable clusters
  stable/kommander/Chart.yaml
  stable/kommander/files/observableclusters-crd.yaml
  stable/kommander/templates/federated-crds.yaml
  stable/kommander/templates/federated-kubeaddons.yaml
  stable/kommander/templates/federated-typeconfigs.yaml
  stable/kommander/templates/hooks-kubeaddons.yaml
  stable/kommander/templates/observable-crd.yaml
  stable/kommander/templates/observablecluster.yaml
  stable/kommander/values.yaml
Labels: ready

#239 Use upstream karma chart
  stable/kommander-karma/Chart.yaml
  stable/kommander-karma/charts/karma-1.1.21.tgz
  stable/kommander-karma/charts/karma-1.2.0.tgz
  stable/kommander-karma/requirements.lock
  stable/kommander-karma/requirements.yaml
  staging/karma/.helmignore
  staging/karma/Chart.yaml
  staging/karma/OWNERS
  staging/karma/README.md
  staging/karma/ci/test-values.yaml
  staging/karma/templates/NOTES.txt
  staging/karma/templates/_helpers.tpl
  staging/karma/templates/configmap.yaml
  staging/karma/templates/deployment.yaml
  staging/karma/templates/ingress.yaml
  staging/karma/templates/service.yaml
  staging/karma/templates/serviceaccount.yaml
  staging/karma/values.yaml
Labels: ready

#244 Adds a chart which can deploy an ingress
  README.md
  staging/generic-ingress/.helmignore
  staging/generic-ingress/Chart.yaml
  staging/generic-ingress/README.md
  staging/generic-ingress/templates/_helpers.tpl
  staging/generic-ingress/templates/ingress.yaml
  staging/generic-ingress/values.yaml
Labels: ready

#243 kommander: use internal kubefed chart (part 2 of crd work)
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-thanos-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/charts/kubefed-0.1.0-rc6.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#250 fix velero deployments
  staging/velero/Chart.yaml
  staging/velero/templates/deployment.yaml
  staging/velero/templates/miniobackend.yaml
Labels: ready

#249 Add karma chart with deployment.annotations parameter
  staging/karma/.helmignore
  staging/karma/Chart.yaml
  staging/karma/OWNERS
  staging/karma/README.md
  staging/karma/ci/test-values.yaml
  staging/karma/templates/NOTES.txt
  staging/karma/templates/_helpers.tpl
  staging/karma/templates/configmap.yaml
  staging/karma/templates/deployment.yaml
  staging/karma/templates/ingress.yaml
  staging/karma/templates/service.yaml
  staging/karma/templates/serviceaccount.yaml
  staging/karma/values.yaml
Labels: ready

#252 [stable/kommander-karma] Bump karma subchart
  stable/kommander-karma/Chart.yaml
  stable/kommander-karma/charts/karma-1.2.0.tgz
  stable/kommander-karma/charts/karma-1.3.0.tgz
  stable/kommander-karma/requirements.lock
  stable/kommander-karma/requirements.yaml
Labels: ready

#254 [stable/kommander] Bump kommander-karma subchart
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma-0.1.1.tgz
  stable/kommander/charts/kommander-karma-0.2.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#251 [opsportal] chore: dependency update and cleanup
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-0.1.35.tgz
  stable/opsportal/charts/kommander-0.2.7.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
  stable/opsportal/values.yaml
Labels: ready

#255 Couple of fixes in istio charts
  staging/istio/Chart.yaml
  staging/istio/charts/grafana/templates/configmap-dashboards.yaml
  staging/istio/charts/prometheus/templates/destinationrule.yaml
  staging/istio/charts/prometheus/values.yaml
  staging/istio/charts/security/templates/clusterrole.yaml
  staging/istio/charts/security/templates/deployment.yaml
  staging/istio/charts/security/templates/job.yaml
Labels: bug, ready

#260 kommander: bump kcl version
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.1.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.2.tgz
  stable/kommander/charts/kommander-karma-0.2.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
Labels: ready

#261 flagger(,-loadtester): Add chart
  staging/flagger/.helmignore
  staging/flagger/Chart.yaml
  staging/flagger/README.md
  staging/flagger/charts/flagger-loadtester/.helmignore
  staging/flagger/charts/flagger-loadtester/Chart.yaml
  staging/flagger/charts/flagger-loadtester/README.md
  staging/flagger/charts/flagger-loadtester/templates/NOTES.txt
  staging/flagger/charts/flagger-loadtester/templates/_helpers.tpl
  staging/flagger/charts/flagger-loadtester/templates/deployment.yaml
  staging/flagger/charts/flagger-loadtester/templates/rbac.yaml
  staging/flagger/charts/flagger-loadtester/templates/service.yaml
  staging/flagger/charts/flagger-loadtester/templates/virtual-node.yaml
  staging/flagger/charts/flagger-loadtester/values.yaml
  staging/flagger/templates/NOTES.txt
  staging/flagger/templates/_helpers.tpl
  staging/flagger/templates/account.yaml
  staging/flagger/templates/crd.yaml
  staging/flagger/templates/dashboard.yaml
  staging/flagger/templates/deployment.yaml
  staging/flagger/templates/job.yaml
  staging/flagger/templates/prometheus.yaml
  staging/flagger/templates/psp.yaml
  staging/flagger/templates/rbac.yaml
  staging/flagger/values.yaml
Labels: ready

#265 [kommander] federated kubeaddons version configurable
  stable/kommander/Chart.yaml
  stable/kommander/templates/federated-kubeaddons.yaml
  stable/kommander/values.yaml
Labels: ready

#268 kommander: multi-cluster cpu/mem dashboard
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/dashboards/k8s-resources-clusters.yaml
Labels: ready

#267 chore: bump kommander/opsportal to image tag 1.149.77
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/values.yaml
Labels: ready

#270 kcl: bump dependency
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.2.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.2.3.tgz
  stable/kommander/charts/kommander-karma-0.2.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#271 kommander: deploy catalog as a subchart in kommander
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma-0.2.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.4.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.3.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/values.yaml
Labels: ready

#272 catalog: manage crd correctly for upgrades
  staging/kubeaddons-catalog/Chart.yaml
  staging/kubeaddons-catalog/files/crd_addonrepository.yaml
  staging/kubeaddons-catalog/templates/crds.yaml
  staging/kubeaddons-catalog/values.yaml
Labels: ready

#273 kommander: update to fixed catalog version
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma-0.2.0.tgz
  stable/kommander/charts/kommander-thanos-0.1.4.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.3.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.4.tgz
  stable/kommander/charts/kubefed-0.0.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#275 dispatch: use apps/v1 api
  stable/dispatch/Chart.yaml
  stable/dispatch/charts/minio/templates/statefulset.yaml
  stable/dispatch/charts/tekton/templates/tekton.yaml
Labels: ready

#278 chore: bump kommander/opsportal image to 1.150.12
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/values.yaml
Labels: ready

#281 awsebs: add allow volume expansion to the storage class
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/templates/storageclass.yaml
  stable/awsebscsiprovisioner/values.yaml
  stable/awsebsprovisioner/Chart.yaml
  stable/awsebsprovisioner/templates/storageclass.yaml
  stable/awsebsprovisioner/values.yaml
Labels: enhancement, ready

#279 kommander: Add kommander prom datasource for thanos querier dashboard
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/dashboards/thanos-query-dashboard.yaml
  stable/kommander/values.yaml
Labels: ready

#283 dispatch: fix api versions and app selectors
  stable/dispatch/Chart.yaml
  stable/dispatch/charts/minio/Chart.yaml
  stable/dispatch/charts/minio/templates/deployment.yaml
  stable/dispatch/charts/tekton/Chart.yaml
  stable/dispatch/charts/tekton/templates/tekton.yaml
Labels: ready

#284 awscsi: fix bug in the chart
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/templates/storageclass.yaml
Labels: bug, ready

#287 awsebs: fix allow volume expansion property
  stable/awsebsprovisioner/Chart.yaml
  stable/awsebsprovisioner/templates/storageclass.yaml
Labels: bug, ready
