Repository mesosphere/charts, pull requests merged in 2020-01, with the labels that each got.

#327 kommander: Add centralized 1.16 clusters dashboard
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/dashboards/k8s-resources-clusters.yaml
Labels: ready

#336 chore: Create helm packages deterministically
  Makefile
Labels: ready

#331 [traefik-forward-auth] reuse secret for session key
  staging/traefik-forward-auth/Chart.yaml
  staging/traefik-forward-auth/templates/deployment.yaml
Labels: ready

#342 [test] Add chart install and upgrade testing
  Makefile
  stable/dex/Chart.yaml
  stable/dex/templates/config-openssl.yaml
  staging/cert-manager-setup/Chart.yaml
  staging/cert-manager-setup/ci/test-values.yaml
  test/ct-e2e.yaml
  test/e2e-kind.sh
  test/kind-config.yaml
Labels: ready

#344 stable/opsportal: bump nginx container to 1.17-alpine
  stable/opsportal/Chart.yaml
  stable/opsportal/templates/landing.yaml
Labels: ready

#345 make: add lint and test targets
  Makefile
Labels: ready

#347 [kommander-karma] [kommander-thanos] Modify UI links
  stable/kommander-karma/Chart.yaml
  stable/kommander-karma/README.md
  stable/kommander-karma/values.yaml
  stable/kommander-thanos/Chart.yaml
  stable/kommander-thanos/README.md
  stable/kommander-thanos/values.yaml
Labels: ready

#349 [prometheus-operator] crd management part 1
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/prometheus-operator/crds.yaml
Labels: ready

#350 [prometheus-operator] crd management part 2
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/prometheus-operator/crds.yaml
Labels: ready

#351 [kommander] Deps bump, change kommander ui paths
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma-0.3.0.tgz
  stable/kommander/charts/kommander-karma-0.3.1.tgz
  stable/kommander/charts/kommander-thanos-0.1.6.tgz
  stable/kommander/charts/kommander-thanos-0.1.7.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.4.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/grafana/dashboards/thanos-query-dashboard.yaml
  stable/kommander/values.yaml
Labels: ready

#348 test: detect teamcity and mount git
  Makefile
  test/e2e-kind.sh
Labels: ci-issues, ready

#354 kommander-karma: Remove trailing slash from ingress path
  stable/kommander-karma/Chart.yaml
  stable/kommander-karma/README.md
  stable/kommander-karma/values.yaml
Labels: ready

#356 kommander: Bump kommander-karma
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma-0.3.1.tgz
  stable/kommander/charts/kommander-karma-0.3.2.tgz
  stable/kommander/charts/kommander-thanos-0.1.7.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#358 chore: gatekeeper set replicas
  staging/gatekeeper/Chart.yaml
  staging/gatekeeper/templates/deployment.yaml
  staging/gatekeeper/values.yaml
Labels: ready

#362 staging/velero: bump minio k8s operator to 1.0.6 (security update)
  staging/velero/Chart.yaml
  staging/velero/templates/miniobackend.yaml
Labels: ready

#365 fix: Fix publishing script
  Makefile
Labels: ready

#357 [nvidia] chore: chart improvements
  staging/nvidia/Chart.yaml
  staging/nvidia/charts/grafana/Chart.yaml
  staging/nvidia/charts/grafana/templates/configmap-dashboards.yaml
  staging/nvidia/charts/grafana/values.yaml
  staging/nvidia/charts/nvidia-dcgm-exporter/Chart.yaml
  staging/nvidia/charts/nvidia-dcgm-exporter/templates/daemonset.yaml
  staging/nvidia/charts/nvidia-dcgm-exporter/templates/tests/test-connection.yaml
  staging/nvidia/charts/nvidia-dcgm-exporter/values.yaml
  staging/nvidia/charts/nvidia-device-plugin/Chart.yaml
  staging/nvidia/charts/nvidia-device-plugin/templates/NOTES.txt
  staging/nvidia/charts/nvidia-device-plugin/templates/daemonset.yaml
  staging/nvidia/charts/nvidia-device-plugin/templates/tests/test-connection.yaml
  staging/nvidia/charts/nvidia-device-plugin/values.yaml
  staging/nvidia/charts/nvidia-driver/Chart.yaml
  staging/nvidia/charts/nvidia-driver/templates/NOTES.txt
  staging/nvidia/charts/nvidia-driver/templates/daemonset.yaml
  staging/nvidia/charts/nvidia-driver/templates/tests/test-connection.yaml
  staging/nvidia/charts/nvidia-driver/values.yaml
  staging/nvidia/requirements.yaml
  staging/nvidia/values.yaml
Labels: ready

#367 chore: Ensure git log timestamp from source branch is used in publish
  Makefile
Labels: ready

#335 [kommander] Move chart to kommander UI repo
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-1.176.3.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/deployment.yaml
  stable/kommander/templates/ingress.yaml
  stable/kommander/templates/roles.yaml
  stable/kommander/templates/service.yaml
  stable/kommander/values.yaml
  test/ct-e2e.yaml
  test/ct.yaml
Labels: ready

#373 chore: Do not add chart sources to master
  Makefile
Labels: ready

#374 chore: Publish to gh-pages
  .gitignore
  Makefile
  hack/chart_destination.sh
Labels: ready

#369 [custom certs] Updates charts to support custom certificate
  staging/dex-k8s-authenticator/Chart.yaml
  staging/dex-k8s-authenticator/html-templates/linux-mac-common.html
  staging/dex-k8s-authenticator/templates/configmap.yaml
  staging/dex-k8s-authenticator/templates/deployment.yaml
  staging/dex-k8s-authenticator/values.yaml
  staging/kube-oidc-proxy/Chart.yaml
  staging/kube-oidc-proxy/templates/deployment.yaml
  staging/kube-oidc-proxy/values.yaml
  staging/traefik-forward-auth/Chart.yaml
  staging/traefik-forward-auth/templates/deployment.yaml
  staging/traefik-forward-auth/values.yaml
  staging/traefik/Chart.yaml
  staging/traefik/templates/configmap.yaml
  staging/traefik/templates/deployment.yaml
  staging/traefik/values.yaml
Labels: ready

#370 [nvidia] fix: use nindent correctly and correct values file
  staging/nvidia/Chart.yaml
  staging/nvidia/charts/nvidia-dcgm-exporter/templates/daemonset.yaml
  staging/nvidia/charts/nvidia-dcgm-exporter/templates/tests/test-connection.yaml
  staging/nvidia/charts/nvidia-device-plugin/templates/daemonset.yaml
  staging/nvidia/charts/nvidia-device-plugin/templates/tests/test-connection.yaml
  staging/nvidia/charts/nvidia-driver/templates/daemonset.yaml
  staging/nvidia/charts/nvidia-driver/templates/tests/test-connection.yaml
  staging/nvidia/values.yaml
Labels: ready

#377 Remove duplicate Grafana dashboards
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/apiserver.yaml
  staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/controlmanager.yaml
  staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/kubelet.yaml
  staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/scheduler.yaml
Labels: ready

#379 Add chart version bump to fix lint failure
  stable/kommander/Chart.yaml
Labels: bug, ready

#378 Retry requests when setting Grafana's home dashboard
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/mesosphere-hooks/post-install-hooks.yaml
Labels: ready

#382 [traefik] added path field to dashboard ingress
  staging/traefik/Chart.yaml
  staging/traefik/templates/dashboard-ingress.yaml
  staging/traefik/values.yaml
Labels: ready

#383 [opsportal] remove application ingress records
  stable/opsportal/Chart.yaml
  stable/opsportal/templates/hooks-roles.yaml
  stable/opsportal/templates/ingress-opsportal.yaml
  stable/opsportal/values.yaml
Labels: ready

#384 kommander-thanos/karma: Cleanup job hook weights
  stable/kommander-karma/Chart.yaml
  stable/kommander-karma/templates/cleanup-configmap.yaml
  stable/kommander-thanos/Chart.yaml
  stable/kommander-thanos/templates/query-stores-configmap.yaml
Labels: ready

#387 chore: add enabled property to deploy tests
  staging/traefik/Chart.yaml
  staging/traefik/templates/tests/test-configmap.yaml
  staging/traefik/templates/tests/test.yaml
  staging/traefik/values.yaml
Labels: ready

#380 [cert-manager-setup] allow for multiple clusterissuers
  staging/cert-manager-setup/Chart.yaml
  staging/cert-manager-setup/ci/general-test-values.yaml
  staging/cert-manager-setup/ci/test-values.yaml
  staging/cert-manager-setup/requirements.yaml
  staging/cert-manager-setup/templates/certificates.yaml
  staging/cert-manager-setup/templates/clusterissuer.yaml
  staging/cert-manager-setup/templates/clusterissuers.yaml
  staging/cert-manager-setup/templates/clusterrole.yaml
  staging/cert-manager-setup/templates/clusterrolebinding.yaml
  staging/cert-manager-setup/templates/issuers.yaml
  staging/cert-manager-setup/templates/post-install-hook-job.yaml
  staging/cert-manager-setup/values.yaml
Labels: ready

#376 [opsportal] Cleanup kommander/opsportal charts
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-1.191.8.tgz
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
  stable/opsportal/charts/kommander-0.2.7.tgz
  stable/opsportal/charts/kommander-ui-1.192.0.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
  stable/opsportal/values.yaml
Labels: ready

#388 fix: bump chart versions (kommander/opsportal)
  stable/kommander/Chart.yaml
  stable/opsportal/Chart.yaml
Labels: bug, ready

#386 kommander: Set Grafana home dashboard in Kommander Grafana
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma-0.3.2.tgz
  stable/kommander/charts/kommander-karma-0.3.3.tgz
  stable/kommander/charts/kommander-thanos-0.1.7.tgz
  stable/kommander/charts/kommander-thanos-0.1.8.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/grafana/hooks-home-dashboard.yaml
  stable/kommander/templates/grafana/opsportal-username-secret.yaml
  stable/kommander/templates/hooks-kubeaddons.yaml
  stable/kommander/values.yaml
Labels: ready
