Repository mesosphere/charts, pull requests merged in 2020-10, with the labels that each got.

#817 chore(kommander): bump yakcl charts to 0.5.0
  stable/kommander/Chart.yaml
  stable/kommander/charts/auto-provisioning-v0.4.7.tgz
  stable/kommander/charts/kommander-federation-v0.4.8.tgz
  stable/kommander/charts/kommander-federation-v0.5.0.tgz
  stable/kommander/charts/kommander-licensing-v0.4.8.tgz
  stable/kommander/charts/kommander-licensing-v0.5.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
Labels: ready

#819 add dns name options for all possible short names
  stable/defaultstorageclass/Chart.yaml
  stable/defaultstorageclass/templates/certificate.yaml
Labels: ready

#818 chore: temp kubefed fork
  staging/kubefed/.gitignore
  staging/kubefed/Chart.lock
  staging/kubefed/Chart.yaml
  staging/kubefed/README.md
  staging/kubefed/charts/controllermanager-0.0.3.tgz
  staging/kubefed/charts/controllermanager/Chart.yaml
  staging/kubefed/charts/controllermanager/templates/install-crds.yaml
  staging/kubefed/charts/controllermanager/templates/service.yaml
  staging/kubefed/charts/controllermanager/values.yaml
  staging/kubefed/crds/crds.yaml
  staging/kubefed/requirement.yaml
  staging/kubefed/subcharts/controllermanager/Chart.yaml
  staging/kubefed/subcharts/controllermanager/crds/crds.yaml
  staging/kubefed/subcharts/controllermanager/templates/_helpers.tpl
  staging/kubefed/subcharts/controllermanager/templates/aggregate_clusterroles.yaml
  staging/kubefed/subcharts/controllermanager/templates/clusterrole.yaml
  staging/kubefed/subcharts/controllermanager/templates/clusterrolebindings.yaml
  staging/kubefed/subcharts/controllermanager/templates/deployments.yaml
  staging/kubefed/subcharts/controllermanager/templates/kubefedconfig.yaml
  staging/kubefed/subcharts/controllermanager/templates/rolebindings.yaml
  staging/kubefed/subcharts/controllermanager/templates/roles.yaml
  staging/kubefed/subcharts/controllermanager/templates/service.yaml
  staging/kubefed/subcharts/controllermanager/templates/serviceaccounts.yaml
  staging/kubefed/subcharts/controllermanager/templates/webhook.yaml
  staging/kubefed/templates/federatedtypeconfig.yaml
  staging/kubefed/templates/install-crds.yaml
  staging/kubefed/values.yaml
Labels: ready

#820 Update Istio to v1.6.11
  staging/istio/Chart.yaml
  staging/istio/values.yaml
Labels: chore, ready

#822 chore: use latest Catalog API release in chart
  staging/kubeaddons-catalog/Chart.yaml
  staging/kubeaddons-catalog/values.yaml
Labels: ready

#824 chore: bump catalog sub-chart in kommander
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubeaddons-catalog-0.1.12.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.13.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#825 chore: bump yakuul
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.5.0.tgz
  stable/kommander/charts/kommander-federation-v0.5.1.tgz
  stable/kommander/charts/kommander-licensing-v0.5.0.tgz
  stable/kommander/charts/kommander-licensing-v0.5.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#826 chore: bump kubeaddons-catalog chart to latest release
  staging/kubeaddons-catalog/Chart.yaml
  staging/kubeaddons-catalog/templates/deployment.yaml
  staging/kubeaddons-catalog/values.yaml
Labels: ready

#829 chore: bump kubeaddons-catalog to latest version
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubeaddons-catalog-0.1.13.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.14.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#827 kubecost: Upgrade kubecost dependency
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.65.0.tgz
  stable/kubecost/charts/cost-analyzer-1.67.1.tgz
  stable/kubecost/requirements.lock
  stable/kubecost/requirements.yaml
  stable/kubecost/values.yaml
Labels: ready

#831 chore: bump the dex-controller memory limit
  stable/dex-controller/Chart.yaml
  stable/dex-controller/values.yaml
Labels: ready

#836 chore: bump kubeaddons-catalog chart to latest release
  staging/kubeaddons-catalog/Chart.yaml
  staging/kubeaddons-catalog/values.yaml
Labels: ready

#837 chore: bump kubeaddons-catalog to latest version
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubeaddons-catalog-0.1.14.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.15.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#833 chore: bump versions of kind, helm, and ct
  Makefile
  test/e2e-kind.sh
Labels: ready

#832 fix: delete federated resources prior to uninstallation
  stable/kommander/Chart.yaml
  stable/kommander/templates/pre-deletion-purger.yaml
Labels: Let me merge it, ready

#839 chore: upgrade yakcl
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.5.1.tgz
  stable/kommander/charts/kommander-federation-v0.5.2.tgz
  stable/kommander/charts/kommander-licensing-v0.5.1.tgz
  stable/kommander/charts/kommander-licensing-v0.5.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#842 chore: backport Makefile changes
  Makefile
Labels: ready

#830 [cert-manager] feat: add upgrade orchestration
  Makefile
  stable/cert-manager-setup/.helmignore
  stable/cert-manager-setup/Chart.yaml
  stable/cert-manager-setup/README.md
  stable/cert-manager-setup/charts/cert-manager-v1.0.3.tgz
  stable/cert-manager-setup/ci/general-test-values.yaml
  stable/cert-manager-setup/ci/test-values.yaml
  stable/cert-manager-setup/requirements.lock
  stable/cert-manager-setup/requirements.yaml
  stable/cert-manager-setup/templates/NOTES.txt
  stable/cert-manager-setup/templates/_helpers.tpl
  stable/cert-manager-setup/templates/certificaterequests-crd-cm.yaml
  stable/cert-manager-setup/templates/certificates-crd-cm.yaml
  stable/cert-manager-setup/templates/certificates.yaml
  stable/cert-manager-setup/templates/challenges-acme-crd-cm.yaml
  stable/cert-manager-setup/templates/clusterissuers-crd-cm.yaml
  stable/cert-manager-setup/templates/clusterissuers.yaml
  stable/cert-manager-setup/templates/clusterrole.yaml
  stable/cert-manager-setup/templates/clusterrolebinding.yaml
  stable/cert-manager-setup/templates/install-crds.yaml
  stable/cert-manager-setup/templates/issuers-crd-cm.yaml
  stable/cert-manager-setup/templates/issuers.yaml
  stable/cert-manager-setup/templates/orders-acme-crd-cm.yaml
  stable/cert-manager-setup/templates/post-install-hook-job.yaml
  stable/cert-manager-setup/templates/v1upgrade.yaml
  stable/cert-manager-setup/values.yaml
  staging/cert-manager-setup/charts/cert-manager-v1.0.1.tgz
  staging/cert-manager-setup/requirements.lock
  test/e2e-kind.sh
  test/helm2/ct-e2e.yaml
Labels: enhancement, ready

#843 chore: update yakcl to v0.3.5
  stable/index.yaml
  stable/kommander-0.8.45.tgz
  staging/index.yaml
Labels: ready

#844 kommander: Upgrade cert-manager resources to v1
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.5.2.tgz
  stable/kommander/charts/kommander-federation-v0.6.0.tgz
  stable/kommander/charts/kommander-licensing-v0.5.2.tgz
  stable/kommander/charts/kommander-licensing-v0.6.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#846 fix: remove - from cert-manager v1upgrade.yaml
  stable/cert-manager-setup/Chart.yaml
  stable/cert-manager-setup/templates/v1upgrade.yaml
Labels: ready

#848 chore: Always use UTC for helm repo index building
  Makefile
Labels: chore, ready

#845 chore: improve macOS handling in Makefile
  Makefile
Labels: chore, ready

#852 Add elasticsearch and elasticsearch-curator forks
  stable/elasticsearch-curator/.helmignore
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/OWNERS
  stable/elasticsearch-curator/README.md
  stable/elasticsearch-curator/ci/default-values.yaml
  stable/elasticsearch-curator/ci/hooks-values.yaml
  stable/elasticsearch-curator/ci/initcontainer-values.yaml
  stable/elasticsearch-curator/templates/NOTES.txt
  stable/elasticsearch-curator/templates/_helpers.tpl
  stable/elasticsearch-curator/templates/configmap.yaml
  stable/elasticsearch-curator/templates/cronjob.yaml
  stable/elasticsearch-curator/templates/hooks/job.install.yaml
  stable/elasticsearch-curator/templates/psp.yml
  stable/elasticsearch-curator/templates/role.yaml
  stable/elasticsearch-curator/templates/rolebinding.yaml
  stable/elasticsearch-curator/templates/serviceaccount.yaml
  stable/elasticsearch-curator/values.yaml
  stable/elasticsearch/.helmignore
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/OWNERS
  stable/elasticsearch/README.md
  stable/elasticsearch/ci/expose-transport-port-on-service-values.yaml
  stable/elasticsearch/ci/extrainitcontainers-values.yaml
  stable/elasticsearch/ci/hooks-values.yaml
  stable/elasticsearch/ci/nonroot-deployment-values.yaml
  stable/elasticsearch/ci/plugin-initcontainer-values.yaml
  stable/elasticsearch/ci/updatestrategy-values.yaml
  stable/elasticsearch/templates/NOTES.txt
  stable/elasticsearch/templates/_helpers.tpl
  stable/elasticsearch/templates/client-auth.yaml
  stable/elasticsearch/templates/client-deployment.yaml
  stable/elasticsearch/templates/client-ingress.yaml
  stable/elasticsearch/templates/client-pdb.yaml
  stable/elasticsearch/templates/client-serviceaccount.yaml
  stable/elasticsearch/templates/client-svc.yaml
  stable/elasticsearch/templates/configmap.yaml
  stable/elasticsearch/templates/data-pdb.yaml
  stable/elasticsearch/templates/data-serviceaccount.yaml
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/job.yaml
  stable/elasticsearch/templates/master-pdb.yaml
  stable/elasticsearch/templates/master-serviceaccount.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
  stable/elasticsearch/templates/master-svc.yaml
  stable/elasticsearch/templates/podsecuritypolicy.yaml
  stable/elasticsearch/templates/role.yaml
  stable/elasticsearch/templates/rolebinding.yaml
  stable/elasticsearch/templates/tests/test-configmap.yaml
  stable/elasticsearch/templates/tests/test.yaml
  stable/elasticsearch/values.yaml
Labels: Let me merge it, ready

#856 Add elasticsearch and elasticsearch-curator forks
  stable/elasticsearch-curator/.helmignore
  stable/elasticsearch-curator/Chart.yaml
  stable/elasticsearch-curator/OWNERS
  stable/elasticsearch-curator/README.md
  stable/elasticsearch-curator/ci/default-values.yaml
  stable/elasticsearch-curator/ci/hooks-values.yaml
  stable/elasticsearch-curator/ci/initcontainer-values.yaml
  stable/elasticsearch-curator/templates/NOTES.txt
  stable/elasticsearch-curator/templates/_helpers.tpl
  stable/elasticsearch-curator/templates/configmap.yaml
  stable/elasticsearch-curator/templates/cronjob.yaml
  stable/elasticsearch-curator/templates/hooks/job.install.yaml
  stable/elasticsearch-curator/templates/psp.yml
  stable/elasticsearch-curator/templates/role.yaml
  stable/elasticsearch-curator/templates/rolebinding.yaml
  stable/elasticsearch-curator/templates/serviceaccount.yaml
  stable/elasticsearch-curator/values.yaml
  stable/elasticsearch/.helmignore
  stable/elasticsearch/Chart.yaml
  stable/elasticsearch/OWNERS
  stable/elasticsearch/README.md
  stable/elasticsearch/ci/expose-transport-port-on-service-values.yaml
  stable/elasticsearch/ci/extrainitcontainers-values.yaml
  stable/elasticsearch/ci/hooks-values.yaml
  stable/elasticsearch/ci/nonroot-deployment-values.yaml
  stable/elasticsearch/ci/plugin-initcontainer-values.yaml
  stable/elasticsearch/ci/updatestrategy-values.yaml
  stable/elasticsearch/templates/NOTES.txt
  stable/elasticsearch/templates/_helpers.tpl
  stable/elasticsearch/templates/client-auth.yaml
  stable/elasticsearch/templates/client-deployment.yaml
  stable/elasticsearch/templates/client-ingress.yaml
  stable/elasticsearch/templates/client-pdb.yaml
  stable/elasticsearch/templates/client-serviceaccount.yaml
  stable/elasticsearch/templates/client-svc.yaml
  stable/elasticsearch/templates/configmap.yaml
  stable/elasticsearch/templates/data-pdb.yaml
  stable/elasticsearch/templates/data-serviceaccount.yaml
  stable/elasticsearch/templates/data-statefulset.yaml
  stable/elasticsearch/templates/job.yaml
  stable/elasticsearch/templates/master-pdb.yaml
  stable/elasticsearch/templates/master-serviceaccount.yaml
  stable/elasticsearch/templates/master-statefulset.yaml
  stable/elasticsearch/templates/master-svc.yaml
  stable/elasticsearch/templates/podsecuritypolicy.yaml
  stable/elasticsearch/templates/role.yaml
  stable/elasticsearch/templates/rolebinding.yaml
  stable/elasticsearch/templates/tests/test-configmap.yaml
  stable/elasticsearch/templates/tests/test.yaml
  stable/elasticsearch/values.yaml
Labels: Let me merge it, ready

#853 external-dns: Add service.labels option
  stable/external-dns/Chart.yaml
  stable/external-dns/templates/service.yaml
  stable/external-dns/values-production.yaml
  stable/external-dns/values.yaml
Labels: ready

#851 defaultstorageclass: Enable metrics collection
  stable/defaultstorageclass/Chart.yaml
  stable/defaultstorageclass/templates/service.yaml
Labels: ready

#857 chore: Bump dex controller dependency
  stable/dex/Chart.yaml
  stable/dex/charts/dex-controller-v0.6.3.tgz
  stable/dex/charts/dex-controller-v0.6.4.tgz
  stable/dex/requirements.lock
  stable/dex/requirements.yaml
Labels: ready

#858 chore: Add config to set svc labels for metric collection
  stable/metallb/Chart.yaml
  stable/metallb/templates/service.yaml
  stable/metallb/values.yaml
Labels: ready

#860 flagger-loadtester: Add chart value service.labels
  staging/flagger/Chart.yaml
  staging/flagger/charts/flagger-loadtester/Chart.yaml
  staging/flagger/charts/flagger-loadtester/README.md
  staging/flagger/charts/flagger-loadtester/templates/service.yaml
  staging/flagger/charts/flagger-loadtester/values.yaml
  staging/flagger/templates/crd.yaml
  staging/flagger/templates/rbac.yaml
Labels: ready

#862 add forked fluent bit
  stable/fluent-bit/Chart.yaml
  stable/fluent-bit/OWNERS
  stable/fluent-bit/README.md
  stable/fluent-bit/templates/NOTES.txt
  stable/fluent-bit/templates/_helpers.tpl
  stable/fluent-bit/templates/cluster-role.yaml
  stable/fluent-bit/templates/cluster-rolebinding.yaml
  stable/fluent-bit/templates/config.yaml
  stable/fluent-bit/templates/daemonset.yaml
  stable/fluent-bit/templates/psp.yaml
  stable/fluent-bit/templates/secret.yaml
  stable/fluent-bit/templates/service.yaml
  stable/fluent-bit/templates/serviceaccount.yaml
  stable/fluent-bit/templates/servicemonitor.yaml
  stable/fluent-bit/templates/tests/test-configmap.yaml
  stable/fluent-bit/templates/tests/test.yaml
  stable/fluent-bit/values.yaml
Labels: Let me merge it, ready

#864 chore: Update yakcl to v0.6.1
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.6.0.tgz
  stable/kommander/charts/kommander-federation-v0.6.1.tgz
  stable/kommander/charts/kommander-licensing-v0.6.0.tgz
  stable/kommander/charts/kommander-licensing-v0.6.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#865 chore: Update yakcl to v0.6.2
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.6.1.tgz
  stable/kommander/charts/kommander-federation-v0.6.2.tgz
  stable/kommander/charts/kommander-licensing-v0.6.1.tgz
  stable/kommander/charts/kommander-licensing-v0.6.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#866 Fix for cleanup job failure when configmap not present
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/mesosphere-hooks/prometheus-cluster-id-hooks.yaml
  staging/prometheus-operator/templates/prometheus/rules/mesosphere-rules/etcd-rules.yaml
  staging/prometheus-operator/templates/prometheus/rules/mesosphere-rules/velero-rules.yaml
Labels: ready

#859 Fix istio image version default
  staging/istio/values.yaml
Labels: bug, ready

#870 bump yackl to 0.6.4
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.6.3.tgz
  stable/kommander/charts/kommander-federation-v0.6.4.tgz
  stable/kommander/charts/kommander-licensing-v0.6.3.tgz
  stable/kommander/charts/kommander-licensing-v0.6.4.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#873 flagger: Revert CRD version upgrade
  staging/flagger/Chart.yaml
  staging/flagger/templates/crd.yaml
Labels: ready

#875 prometheus_operator: use forked hosted charts
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/charts/grafana-5.0.26.tgz
  staging/prometheus-operator/charts/grafana-5.3.6.tgz
  staging/prometheus-operator/charts/kube-state-metrics-2.8.14.tgz
  staging/prometheus-operator/charts/kube-state-metrics-2.8.8.tgz
  staging/prometheus-operator/charts/prometheus-node-exporter-1.10.0.tgz
  staging/prometheus-operator/charts/prometheus-node-exporter-1.9.1.tgz
  staging/prometheus-operator/requirements.lock
  staging/prometheus-operator/requirements.yaml
Labels: ready

#876 kommander: use forked hosted charts
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma/Chart.yaml
  stable/kommander/charts/kommander-karma/requirements.lock
  stable/kommander/charts/kommander-karma/requirements.yaml
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready
