Repository mesosphere/charts, pull requests merged in 2020-09, with the labels that each got.

#771 feat: handle airgapped deployment
  stable/kommander/Chart.yaml
  stable/kommander/charts/auto-provisioning-v0.4.2.tgz
  stable/kommander/charts/auto-provisioning-v0.4.3.tgz
  stable/kommander/charts/kommander-federation-v0.4.2.tgz
  stable/kommander/charts/kommander-federation-v0.4.3.tgz
  stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
  stable/kommander/charts/kommander-licensing-v0.4.2.tgz
  stable/kommander/charts/kommander-licensing-v0.4.3.tgz
  stable/kommander/charts/kommander-thanos/templates/federated-addon.yaml
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/kubecost/federated-addon.yaml
  stable/kommander/values.yaml
Labels: ready

#773 replace deployment when upgrading
  staging/cert-manager-setup/Chart.yaml
  staging/cert-manager-setup/cert-manager/.helmignore
  staging/cert-manager-setup/cert-manager/Chart.yaml
  staging/cert-manager-setup/cert-manager/OWNERS
  staging/cert-manager-setup/cert-manager/README.md
  staging/cert-manager-setup/cert-manager/cainjector/.helmignore
  staging/cert-manager-setup/cert-manager/cainjector/Chart.yaml
  staging/cert-manager-setup/cert-manager/cainjector/templates/NOTES.txt
  staging/cert-manager-setup/cert-manager/cainjector/templates/_helpers.tpl
  staging/cert-manager-setup/cert-manager/cainjector/templates/deployment.yaml
  staging/cert-manager-setup/cert-manager/cainjector/templates/rbac.yaml
  staging/cert-manager-setup/cert-manager/cainjector/templates/serviceaccount.yaml
  staging/cert-manager-setup/cert-manager/cainjector/values.yaml
  staging/cert-manager-setup/cert-manager/charts/cainjector/.helmignore
  staging/cert-manager-setup/cert-manager/charts/cainjector/Chart.yaml
  staging/cert-manager-setup/cert-manager/charts/cainjector/templates/NOTES.txt
  staging/cert-manager-setup/cert-manager/charts/cainjector/templates/_helpers.tpl
  staging/cert-manager-setup/cert-manager/charts/cainjector/templates/deployment.yaml
  staging/cert-manager-setup/cert-manager/charts/cainjector/templates/rbac.yaml
  staging/cert-manager-setup/cert-manager/charts/cainjector/templates/serviceaccount.yaml
  staging/cert-manager-setup/cert-manager/charts/cainjector/values.yaml
  staging/cert-manager-setup/cert-manager/requirements.yaml
  staging/cert-manager-setup/cert-manager/templates/NOTES.txt
  staging/cert-manager-setup/cert-manager/templates/_helpers.tpl
  staging/cert-manager-setup/cert-manager/templates/deployment.yaml
  staging/cert-manager-setup/cert-manager/templates/rbac.yaml
  staging/cert-manager-setup/cert-manager/templates/service.yaml
  staging/cert-manager-setup/cert-manager/templates/serviceaccount.yaml
  staging/cert-manager-setup/cert-manager/templates/servicemonitor.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-apiservice.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-deployment.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-mutating-webhook.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-rbac.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-service.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-serviceaccount.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-validating-webhook.yaml
  staging/cert-manager-setup/cert-manager/values.yaml
  staging/cert-manager-setup/charts/cert-manager-v0.10.1.tgz
  staging/cert-manager-setup/charts/cert-manager-v0.10.2.tgz
  staging/cert-manager-setup/ci/general-test-values.yaml
  staging/cert-manager-setup/files/crds.yaml
  staging/cert-manager-setup/requirements.lock
  staging/cert-manager-setup/requirements.yaml
  staging/cert-manager-setup/templates/install-crds.yaml
Labels: ready

#774 kubecost: Upgrade kubecost dep to 1.64.0
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.63.0.tgz
  stable/kubecost/charts/cost-analyzer-1.64.0.tgz
  stable/kubecost/requirements.lock
  stable/kubecost/requirements.yaml
Labels: ready

#775 Exposing 'registriesSkippingTagResolving' parameter for KNative Serving
  staging/knative/Chart.yaml
  staging/knative/charts/serving/Chart.yaml
  staging/knative/charts/serving/templates/serving.yaml
  staging/knative/charts/serving/values.yaml
  staging/knative/requirements.yaml
  staging/knative/values.yaml
Labels: ready

#778 fix: usage of kubectl:latest
  staging/cert-manager-setup/Chart.yaml
  staging/cert-manager-setup/templates/install-crds.yaml
  staging/cert-manager-setup/templates/post-install-hook-job.yaml
  staging/flagger/Chart.yaml
  staging/flagger/templates/job.yaml
  staging/traefik/Chart.yaml
  staging/traefik/templates/tests/test-certificate.yaml
  staging/traefik/templates/tests/test-customCertificate.yaml
Labels: bug, ready

#781 revert cert-manager-setup changes from #773
  staging/cert-manager-setup/Chart.yaml
  staging/cert-manager-setup/cert-manager/.helmignore
  staging/cert-manager-setup/cert-manager/Chart.yaml
  staging/cert-manager-setup/cert-manager/OWNERS
  staging/cert-manager-setup/cert-manager/README.md
  staging/cert-manager-setup/cert-manager/cainjector/.helmignore
  staging/cert-manager-setup/cert-manager/cainjector/Chart.yaml
  staging/cert-manager-setup/cert-manager/cainjector/templates/NOTES.txt
  staging/cert-manager-setup/cert-manager/cainjector/templates/_helpers.tpl
  staging/cert-manager-setup/cert-manager/cainjector/templates/deployment.yaml
  staging/cert-manager-setup/cert-manager/cainjector/templates/rbac.yaml
  staging/cert-manager-setup/cert-manager/cainjector/templates/serviceaccount.yaml
  staging/cert-manager-setup/cert-manager/cainjector/values.yaml
  staging/cert-manager-setup/cert-manager/charts/cainjector/.helmignore
  staging/cert-manager-setup/cert-manager/charts/cainjector/Chart.yaml
  staging/cert-manager-setup/cert-manager/charts/cainjector/templates/NOTES.txt
  staging/cert-manager-setup/cert-manager/charts/cainjector/templates/_helpers.tpl
  staging/cert-manager-setup/cert-manager/charts/cainjector/templates/deployment.yaml
  staging/cert-manager-setup/cert-manager/charts/cainjector/templates/rbac.yaml
  staging/cert-manager-setup/cert-manager/charts/cainjector/templates/serviceaccount.yaml
  staging/cert-manager-setup/cert-manager/charts/cainjector/values.yaml
  staging/cert-manager-setup/cert-manager/requirements.yaml
  staging/cert-manager-setup/cert-manager/templates/NOTES.txt
  staging/cert-manager-setup/cert-manager/templates/_helpers.tpl
  staging/cert-manager-setup/cert-manager/templates/deployment.yaml
  staging/cert-manager-setup/cert-manager/templates/rbac.yaml
  staging/cert-manager-setup/cert-manager/templates/service.yaml
  staging/cert-manager-setup/cert-manager/templates/serviceaccount.yaml
  staging/cert-manager-setup/cert-manager/templates/servicemonitor.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-apiservice.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-deployment.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-mutating-webhook.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-rbac.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-service.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-serviceaccount.yaml
  staging/cert-manager-setup/cert-manager/templates/webhook-validating-webhook.yaml
  staging/cert-manager-setup/cert-manager/values.yaml
  staging/cert-manager-setup/charts/cert-manager-v0.10.1.tgz
  staging/cert-manager-setup/charts/cert-manager-v0.10.2.tgz
  staging/cert-manager-setup/ci/general-test-values.yaml
  staging/cert-manager-setup/files/crds.yaml
  staging/cert-manager-setup/requirements.lock
  staging/cert-manager-setup/requirements.yaml
  staging/cert-manager-setup/templates/install-crds.yaml
Labels: ready

#777 Update Istio to v1.6.8
  CODEOWNERS
  staging/istio/Chart.yaml
  staging/istio/values.yaml
Labels: ready, security

#776 chore: bump helm 2 version
  .gitignore
  Makefile
Labels: chore, ready

#784 fix: bump mtls-proxy version
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
  stable/kommander/charts/kommander-thanos/templates/federated-addon.yaml
  stable/kommander/templates/kubecost/federated-addon.yaml
Labels: ready

#785 fix:[nvidia] Add Centos 7.7 Vault Repo for Konvoy 1.5 support
  staging/nvidia/Chart.yaml
  staging/nvidia/charts/nvidia-driver/Chart.yaml
  staging/nvidia/charts/nvidia-driver/templates/configmap.yaml
  staging/nvidia/requirements.yaml
Labels: ready

#786 chore: bump yakcl to v0.4.5
  stable/kommander/Chart.yaml
  stable/kommander/charts/auto-provisioning-v0.4.4.tgz
  stable/kommander/charts/auto-provisioning-v0.4.5.tgz
  stable/kommander/charts/kommander-federation-v0.4.4.tgz
  stable/kommander/charts/kommander-federation-v0.4.5.tgz
  stable/kommander/charts/kommander-licensing-v0.4.4.tgz
  stable/kommander/charts/kommander-licensing-v0.4.5.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#783 Feat: Add new vsphere-csi-driver chart
  stable/vsphere-csi-driver/Chart.yaml
  stable/vsphere-csi-driver/templates/NOTES.txt
  stable/vsphere-csi-driver/templates/_helper.tpl
  stable/vsphere-csi-driver/templates/controller.yaml
  stable/vsphere-csi-driver/templates/node.yaml
  stable/vsphere-csi-driver/templates/rbac.yaml
  stable/vsphere-csi-driver/templates/serviceaccount.yaml
  stable/vsphere-csi-driver/templates/storageclass.yaml
  stable/vsphere-csi-driver/values.yaml
  test/helm2/ct-e2e.yaml
  test/helm3/ct-e2e.yaml
Labels: ready

#789 chore: Upgrade kubecost dep to 1.65.0
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.64.0.tgz
  stable/kubecost/charts/cost-analyzer-1.65.0.tgz
  stable/kubecost/requirements.lock
  stable/kubecost/requirements.yaml
Labels: ready

#790 kommander: Update kubecost dep
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.1.12.tgz
  stable/kommander/charts/kubecost-0.1.14.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#792 [D2IQ-71816] Update Istio Chart to v1.6.9
  staging/istio/Chart.yaml
  staging/istio/values.yaml
Labels: chore, ready

#793 kubecost: Include new savings rule
  stable/kubecost/Chart.yaml
  stable/kubecost/values.yaml
Labels: ready

#794 kommander: Bump kubecost dep
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.1.14.tgz
  stable/kommander/charts/kubecost-0.1.15.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
Labels: ready

#800 chore: bump yakcl to v0.4.6
  stable/kommander/Chart.yaml
  stable/kommander/charts/auto-provisioning-v0.4.5.tgz
  stable/kommander/charts/auto-provisioning-v0.4.6.tgz
  stable/kommander/charts/kommander-federation-v0.4.5.tgz
  stable/kommander/charts/kommander-federation-v0.4.6.tgz
  stable/kommander/charts/kommander-licensing-v0.4.5.tgz
  stable/kommander/charts/kommander-licensing-v0.4.6.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#802 [dex] chore: cert-manager resources check version installed
  stable/dex/Chart.yaml
  stable/dex/charts/dex-controller-v0.6.1.tgz
  stable/dex/charts/dex-controller-v0.6.2.tgz
  stable/dex/requirements.lock
  stable/dex/requirements.yaml
  stable/dex/templates/certificate.yaml
Labels: Let me merge it, ready

#806 cert-manager: Use clusterissuers instead of deprecated clusterissuer
  staging/cert-manager-setup/Chart.yaml
  staging/cert-manager-setup/README.md
  staging/cert-manager-setup/ci/test-values.yaml
  staging/cert-manager-setup/values.yaml
Labels: ready

#808 Update kommander subcharts to v0.4.8
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.4.7.tgz
  stable/kommander/charts/kommander-federation-v0.4.8.tgz
  stable/kommander/charts/kommander-licensing-v0.4.7.tgz
  stable/kommander/charts/kommander-licensing-v0.4.8.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: bug, ready

#807 [defaultstorageclass] chore: configure to work on cert-manager v1
  stable/defaultstorageclass/Chart.yaml
  stable/defaultstorageclass/templates/certificate.yaml
  stable/defaultstorageclass/templates/validatingwebhookconfiguration.yaml
Labels: ready

#811 [dex] chore: dex-controller version bump
  stable/dex/Chart.yaml
  stable/dex/charts/dex-controller-v0.6.2.tgz
  stable/dex/charts/dex-controller-v0.6.3.tgz
  stable/dex/requirements.lock
  stable/dex/requirements.yaml
Labels: ready

#814 [kop] chore: configure to work on cert-manager v1
  staging/kube-oidc-proxy/Chart.yaml
  staging/kube-oidc-proxy/templates/certificate.yaml
Labels: ready

#813 [gatekeeper]: chore: configure to work on cert-manager v1
  staging/gatekeeper/Chart.yaml
  staging/gatekeeper/templates/validatingwebhook.yaml
Labels: ready

#815 cert-manager: Create intermediate ca for CI
  staging/cert-manager-setup/Chart.yaml
  staging/cert-manager-setup/ci/test-values.yaml
  staging/cert-manager-setup/requirements.lock
Labels: ready

#805 traefik: Update extrasteps version to use cert-manager v1
  staging/traefik/Chart.yaml
  staging/traefik/README.md
  staging/traefik/ci/test-values.yaml
  staging/traefik/templates/certificate.yaml
  staging/traefik/templates/init-cert-rbac.yaml
  staging/traefik/templates/tests/test-certificate.yaml
  staging/traefik/values.yaml
Labels: ready

#804 fix: override cert-manager release name to work with hardcoded values in CRD files
  staging/cert-manager-setup/Chart.yaml
  staging/cert-manager-setup/files/certificaterequests.cert-manager.io-crd.yaml
  staging/cert-manager-setup/files/certificates.cert-manager.io-crd.yaml
  staging/cert-manager-setup/files/challenges.acme.cert-manager.io-crd.yaml
  staging/cert-manager-setup/files/clusterissuers.cert-manager.io-crd.yaml
  staging/cert-manager-setup/files/issuers.cert-manager.io-crd.yaml
  staging/cert-manager-setup/files/orders.acme.cert-manager.io-crd.yaml
  staging/cert-manager-setup/templates/certificaterequests-crd-cm.yaml
  staging/cert-manager-setup/templates/certificates-crd-cm.yaml
  staging/cert-manager-setup/templates/challenges-acme-crd-cm.yaml
  staging/cert-manager-setup/templates/clusterissuers-crd-cm.yaml
  staging/cert-manager-setup/templates/install-crds.yaml
  staging/cert-manager-setup/templates/issuers-crd-cm.yaml
  staging/cert-manager-setup/templates/orders-acme-crd-cm.yaml
Labels: ready

#816 kommander: Reset kubecost thanos loglevel to default (info)
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: ready
