Repository mesosphere/charts, pull requests merged in 2020-06, with the labels that each got.

#613 Bump Kommander / Opsportal UI
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-3.90.0.tgz
  stable/kommander/charts/kommander-ui-3.96.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-3.85.0.tgz
  stable/opsportal/charts/kommander-ui-3.96.0.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#612 cluster-autoscaler: Add grafana dashboard
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/charts/grafana/Chart.yaml
  stable/cluster-autoscaler/charts/grafana/templates/_helpers.tpl
  stable/cluster-autoscaler/charts/grafana/templates/k8s-autoscaler.yaml
  stable/cluster-autoscaler/charts/grafana/values.yaml
  test/e2e-kind.sh
Labels: ready

#609 kommander: Bump thanos to 0.3.21
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-thanos/charts/thanos-0.3.20.tgz
  stable/kommander/charts/kommander-thanos/charts/thanos-0.3.21.tgz
  stable/kommander/charts/kommander-thanos/requirements.lock
  stable/kommander/charts/kommander-thanos/requirements.yaml
Labels: ready

#608 kommander: Update karma dep to 1.4.1
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma/charts/karma-1.4.0.tgz
  stable/kommander/charts/kommander-karma/charts/karma-1.4.1.tgz
  stable/kommander/charts/kommander-karma/requirements.lock
  stable/kommander/charts/kommander-karma/requirements.yaml
Labels: ready

#621 kommander: Update yakcl to v0.0.7
  stable/kommander/Chart.yaml
  stable/kommander/charts/yakcl-federation-v0.0.4.tgz
  stable/kommander/charts/yakcl-federation-v0.0.7.tgz
  stable/kommander/charts/yakcl-licensing-v0.0.4.tgz
  stable/kommander/charts/yakcl-licensing-v0.0.7.tgz
  stable/kommander/charts/yakcl-provisioning-v0.0.4.tgz
  stable/kommander/charts/yakcl-provisioning-v0.0.7.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#622 kommander: Override kubecost component names
  Dispatchfile
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: ready

#626 [kommander] Rewrite Kubecost URL to include trailing slash
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: ready

#632 kommander: Update kubecost chart version
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.1.4.tgz
  stable/kommander/charts/kubecost-0.1.5.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#635 kommander: Upgrade grafana subchart
  stable/kommander/Chart.yaml
  stable/kommander/charts/grafana-4.5.1.tgz
  stable/kommander/charts/grafana-4.6.3.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#637 kommander: update ingress priority for Grafana
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: bug, ready

#636 kubecost: Fix prom server cm name
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.60.0.tgz
  stable/kubecost/charts/cost-analyzer-1.60.1.tgz
  stable/kubecost/requirements.lock
  stable/kubecost/requirements.yaml
  stable/kubecost/templates/_helpers.tpl
  stable/kubecost/templates/hooks-clusterid.yaml
Labels: bug, ready

#640 kommander: Bump kubecost to fix post-install failures
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.1.5.tgz
  stable/kommander/charts/kubecost-0.1.6.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#644 update the catalog CRD to support the kubeaddons v1beta2 api
  staging/kubeaddons-catalog/Chart.yaml
  staging/kubeaddons-catalog/files/crd_addonrepository.yaml
Labels: ready

#645 update kommander to use the new catalog chart with the CRD to support he kubeaddons v1beta2 api
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubeaddons-catalog-0.1.10.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.9.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#643 fix: set some initial limits to prometheus components
  stable/kubecost/Chart.yaml
  stable/kubecost/values.yaml
Labels: bug, ready

#648 fix: traefik job name must be unique for upgrades to succeed
  staging/traefik/Chart.yaml
  staging/traefik/templates/init-cert-job.yaml
Labels: ready

#649 chore: bumps yakcl to v0.1.2
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.1.0.tgz
  stable/kommander/charts/kommander-federation-v0.1.2.tgz
  stable/kommander/charts/kommander-licensing-v0.1.0.tgz
  stable/kommander/charts/kommander-licensing-v0.1.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: chore, ready

#650 [kubeaddons-catalog] chore: bump catalog image to version 0.8.6
  staging/kubeaddons-catalog/Chart.yaml
  staging/kubeaddons-catalog/files/crd_addonrepository.yaml
  staging/kubeaddons-catalog/values.yaml
Labels: ready

#655 opsportal: fix a typo that prevents upgrades
  stable/opsportal/Chart.yaml
  stable/opsportal/templates/kibana-roles.yaml
Labels: ready

#653 [kommander] fix: catalog fixes including a chart issue
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubeaddons-catalog-0.1.10.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.11.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#634 fix: add clippy js for clipboard support
  staging/dex-k8s-authenticator/Chart.yaml
  staging/dex-k8s-authenticator/html-templates/plugin.html
Labels: ready

#654 kommander: Upgrade kubecost dep
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.1.6.tgz
  stable/kommander/charts/kubecost-0.1.7.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#657 cluster-autoscaler: Revert grafana dashboard
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/charts/grafana/Chart.yaml
  stable/cluster-autoscaler/charts/grafana/templates/_helpers.tpl
  stable/cluster-autoscaler/charts/grafana/templates/k8s-autoscaler.yaml
  stable/cluster-autoscaler/charts/grafana/values.yaml
  test/e2e-kind.sh
Labels: ready

#658 prometheus-operator: Add autoscaler dashboard
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/grafana/dashboards/mesosphere-dashboards/autoscalerdashboard.yaml
  staging/prometheus-operator/values.yaml
Labels: ready

#656 kommander: Fix missing kubecost cm on upgrade
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-thanos/Chart.yaml
  stable/kommander/charts/kommander-thanos/templates/query-stores-configmap.yaml
  stable/kommander/templates/kubecost/kubecost-query-stores-configmap.yaml
Labels: ready

#659 kommander: cm script bash fix
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-thanos/templates/query-stores-configmap.yaml
  stable/kommander/templates/kubecost/kubecost-query-stores-configmap.yaml
Labels: ready

#661 prometheus-operator: Fix KubePodNotReady prometheus rule
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/prometheus/rules-1.14/kubernetes-apps.yaml
Labels: bug, ready

#664 feat: adds caSecretName key to konvoyconfig
  staging/konvoyconfig/Chart.yaml
  staging/konvoyconfig/templates/configmap.yaml
  staging/konvoyconfig/values.yaml
Labels: ready

#667 fix: update release label in service monitors
  staging/istio/Chart.yaml
  staging/istio/charts/prometheus-operator/templates/servicemonitors.yaml
  staging/istio/charts/security/templates/istio-cacert-job.yaml
Labels: ready

#668 chore: bump UI and YAKCL
  stable/kommander/Chart.yaml
  stable/kommander/charts/auto-provisioning-v0.1.0.tgz
  stable/kommander/charts/auto-provisioning-v0.1.3.tgz
  stable/kommander/charts/kommander-federation-v0.1.2.tgz
  stable/kommander/charts/kommander-federation-v0.1.3.tgz
  stable/kommander/charts/kommander-licensing-v0.1.2.tgz
  stable/kommander/charts/kommander-licensing-v0.1.3.tgz
  stable/kommander/charts/kommander-ui-3.111.0.tgz
  stable/kommander/charts/kommander-ui-3.122.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#669 traefik: revert change to include extraServicePorts for velero and metrics
  staging/traefik/Chart.yaml
  staging/traefik/templates/service.yaml
  staging/traefik/values.yaml
Labels: ready

#671 chore: bump yakcl in Kommander to v0.1.4
  stable/kommander/Chart.yaml
  stable/kommander/charts/auto-provisioning-v0.1.3.tgz
  stable/kommander/charts/auto-provisioning-v0.1.4.tgz
  stable/kommander/charts/kommander-federation-v0.1.3.tgz
  stable/kommander/charts/kommander-federation-v0.1.4.tgz
  stable/kommander/charts/kommander-licensing-v0.1.3.tgz
  stable/kommander/charts/kommander-licensing-v0.1.4.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#673 prometheus-operator: Move apiserver availability rules to new group with 3m interval
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/grafana/dashboards-1.14/apiserver.yaml
  staging/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver.rules.yaml
Labels: ready
