Repository mesosphere/charts, pull requests merged in 2020-04, with the labels that each got.

#533 chore: use autodiscovery for konvoy provider
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/values.yaml
Labels: do not merge, ready

#536 chore: Bump kcl 0.5.1 -> 0.5.2
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.1.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#537 [kommander] bump UI
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-3.16.5.tgz
  stable/kommander/charts/kommander-ui-3.26.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#538 chore: update kommander appversion
  stable/kommander/Chart.yaml
Labels: ready

#535 Plugin Instruction pages
  staging/dex-k8s-authenticator/Chart.yaml
  staging/dex-k8s-authenticator/html-templates/kubeconfig.tmpl
  staging/dex-k8s-authenticator/html-templates/kubectl-plugin-instructions.html
  staging/dex-k8s-authenticator/html-templates/plugin.html
  staging/dex-k8s-authenticator/templates/configmap.yaml
Labels: ready

#540 kommander: Create kubecost ns hook
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-3.25.5.tgz
  stable/kommander/charts/kommander-ui-3.26.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/hooks-kubeaddons.yaml
  stable/kommander/templates/hooks-kubecost.yaml
  stable/kommander/values.yaml
Labels: ready

#541 chore(opsportal): bump ui 3.16.5 -> 3.25.5
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-3.16.5.tgz
  stable/opsportal/charts/kommander-ui-3.25.5.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#542 [opsportal/kommander] bump ui 3.25.5 -> 3.27.2
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-3.25.5.tgz
  stable/kommander/charts/kommander-ui-3.27.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-3.25.5.tgz
  stable/opsportal/charts/kommander-ui-3.27.2.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#546 fix: Kind already supports PVC (e2e tests)
  test/e2e-kind.sh
Labels: ready

#547 velero: backport of extraArgs fix: #20091
  staging/velero/Chart.yaml
  staging/velero/charts/minio/Chart.yaml
  staging/velero/charts/minio/templates/_helpers.tpl
  staging/velero/charts/minio/templates/deployment.yaml
  staging/velero/charts/minio/templates/statefulset.yaml
  staging/velero/requirements.lock
  staging/velero/requirements.yaml
Labels: ready

#543 kubecost: Add parent chart
  stable/kubecost/.helmignore
  stable/kubecost/Chart.yaml
  stable/kubecost/README.md
  stable/kubecost/charts/cost-analyzer-1.56.1.tgz
  stable/kubecost/requirements.lock
  stable/kubecost/requirements.yaml
  stable/kubecost/templates/_helpers.tpl
  stable/kubecost/templates/hooks-clusterid.yaml
  stable/kubecost/values.yaml
  test/ct-e2e.yaml
  test/ct.yaml
Labels: ready

#551 [D2IQ-66835] Prom Operator v0.35.1
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/values.yaml
Labels: bug, ready

#552 chore: bump KCL dependency in kommander chart
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.2.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.3.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: chore, ready

#549 chore: bump kind image version of CI exclude test directory from grep result
  Makefile
  test/e2e-kind.sh
Labels: ready

#558 chore: bump kcl version
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.3.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.4.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#560 fix: metrics endpoint
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/templates/service.yaml
  stable/cluster-autoscaler/values.yaml
Labels: bug, ready

#563 chore: add kubeaddons selector
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/values.yaml
Labels: ready

#565 chore: bump kcl v0.5.5
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.4.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.5.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
Labels: ready

#566 [kommander] chore: update version of kcl to v0.5.6
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.5.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.6.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#568 chore: bump kcl
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.6.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.7.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready
