Repository mesosphere/charts, pull requests merged in 2020-02, with the labels that each got.

#395 kommander: Upgrade Grafana subchart
  stable/kommander/Chart.yaml
  stable/kommander/charts/grafana-3.8.19.tgz
  stable/kommander/charts/grafana-4.5.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/grafana/hooks-home-dashboard.yaml
Labels: ready

#397 kommander: Fix upgrade bug
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/opsportal-username-secret.yaml
  stable/kommander/templates/hooks-kubeaddons.yaml
Labels: wip

#385 [tfa] add rbac option
  staging/traefik-forward-auth/Chart.yaml
  staging/traefik-forward-auth/templates/clusterrole.yaml
  staging/traefik-forward-auth/templates/deployment.yaml
  staging/traefik-forward-auth/values.yaml
Labels: ready

#398 [traefik] add dashboard RBAC roles
  staging/traefik/templates/dashboard-roles.yaml
  staging/traefik/values.yaml
Labels: ready

#401 [opsportal,kommander] fix: bump kommander ui to fix missing SA upgrade
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-1.192.2.tgz
  stable/kommander/charts/kommander-ui-1.192.3.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-1.192.2.tgz
  stable/opsportal/charts/kommander-ui-1.192.3.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#400 [prometheus] add prometheus RBAC roles
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/ingress-rbac/alertmanager.yaml
  staging/prometheus-operator/templates/ingress-rbac/grafana.yaml
  staging/prometheus-operator/templates/ingress-rbac/prometheus.yaml
  staging/prometheus-operator/values.yaml
Labels: ready

#399 [opsportal] add opsportal and kibana RBAC roles
  stable/opsportal/templates/ingress-opsportal-roles.yaml
  stable/opsportal/templates/kibana-roles.yaml
  stable/opsportal/values.yaml
Labels: ready

#394 azuredisk: bump version to 0.5.0
  stable/azuredisk-csi-driver/Chart.yaml
  stable/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  stable/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  stable/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  stable/azuredisk-csi-driver/values.yaml
Labels: enhancement

#390 [opsportal] remove all ingress record references
  stable/opsportal/Chart.yaml
  stable/opsportal/templates/ingress-opsportal.yaml
  stable/opsportal/values.yaml
Labels: blocked

#404 chore: remove worker-threads flag
  stable/azuredisk-csi-driver/Chart.yaml
  stable/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
Labels: ready

#406 CI: changed branch since we are working off master now
  Makefile
  test/ct-e2e.yaml
  test/ct.yaml
Labels: ready

#405 [opsportal, kube-oidc-proxy] Chart updates
  stable/opsportal/Chart.yaml
  stable/opsportal/templates/ingress-opsportal-roles.yaml
  stable/opsportal/values.yaml
  staging/kube-oidc-proxy/Chart.yaml
  staging/kube-oidc-proxy/templates/clusterrole.yaml
  staging/kube-oidc-proxy/values.yaml
Labels: ready

#408 opsportal: bump extra-steps to fix RBAC bug
  stable/opsportal/Chart.yaml
  stable/opsportal/values.yaml
Labels: ready

#407 CI: create an lb to test out some charts
  test/e2e-kind.sh
Labels: ready

#409 Use consistent naming for opsportal roles
  stable/opsportal/Chart.yaml
  stable/opsportal/templates/ingress-opsportal-roles.yaml
  stable/opsportal/templates/kibana-roles.yaml
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/ingress-rbac/alertmanager.yaml
  staging/prometheus-operator/templates/ingress-rbac/grafana.yaml
  staging/prometheus-operator/templates/ingress-rbac/prometheus.yaml
  staging/traefik/Chart.yaml
  staging/traefik/templates/dashboard-roles.yaml
Labels: ready

#413 chore(kommander): bump KCL to v0.4.0
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.3.5.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#411 [kubefed] enable the use of cert-manager to produce web-hook certs
  staging/kubefed/Chart.yaml
  staging/kubefed/charts/controllermanager/templates/deployments.yaml
  staging/kubefed/charts/controllermanager/templates/webhook.yaml
  staging/kubefed/charts/controllermanager/values.yaml
  staging/kubefed/requirement.yaml
  staging/kubefed/values.yaml
Labels: ready

#419 chore: bump kcl to 0.4.2
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.0.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.2.tgz
  stable/kommander/charts/kommander-ui-1.192.3.tgz
  stable/kommander/charts/kommander-ui-2.21.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#423 chore(kommander): bump KCL to v0.4.3, UI to 2.24.2
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.2.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.3.tgz
  stable/kommander/charts/kommander-ui-2.21.0.tgz
  stable/kommander/charts/kommander-ui-2.24.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#425 Update kommander chart dependencies to latest releases
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.3.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.4.tgz
  stable/kommander/charts/kommander-ui-2.24.13.tgz
  stable/kommander/charts/kommander-ui-2.24.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#429 dex: bump dex controller to v0.4.2
  stable/dex/Chart.yaml
  stable/dex/charts/dex-controller-v0.4.1.tgz
  stable/dex/charts/dex-controller-v0.4.2.tgz
  stable/dex/requirements.lock
  stable/dex/requirements.yaml
Labels: ready

#431 chore: update kommander and ops portal
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-2.25.11.tgz
  stable/kommander/charts/kommander-ui-2.26.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-1.192.3.tgz
  stable/opsportal/charts/kommander-ui-2.26.1.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#442 Bumps UI to 2.27.8
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-2.26.1.tgz
  stable/kommander/charts/kommander-ui-2.27.8.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-2.26.1.tgz
  stable/opsportal/charts/kommander-ui-2.27.8.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
  stable/opsportal/values.yaml
Labels: ready

#441 chore: increase memory limit to avoid OOM issues
  staging/kubeaddons-catalog/Chart.yaml
  staging/kubeaddons-catalog/values.yaml
Labels: bug, ready

#444 chore: bump kubeaddons-catalog version
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubeaddons-catalog-0.1.4.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.5.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#438 [mtls-proxy] Add annotations option
  stable/mtls-proxy/Chart.yaml
  stable/mtls-proxy/templates/deployment.yaml
  stable/mtls-proxy/values.yaml
Labels: ready

#443 [kommander-karma] [kommander-thanos] Add secret reloader annotations
  stable/kommander-karma/Chart.yaml
  stable/kommander-karma/templates/federated-addon.yaml
  stable/kommander-thanos/Chart.yaml
  stable/kommander-thanos/templates/federated-addon.yaml
Labels: ready

#430 Add Dispatchfile
  Dispatchfile
  test/e2e-kind.sh
  test/kind-config.yaml
Labels: ready

#446 kommander: Bump kommander-karma and kommander-thanos deps
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma-0.3.3.tgz
  stable/kommander/charts/kommander-karma-0.3.4.tgz
  stable/kommander/charts/kommander-thanos-0.1.8.tgz
  stable/kommander/charts/kommander-thanos-0.1.9.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#445 [chore] update kommander catalog api
  staging/kubeaddons-catalog/Chart.yaml
  staging/kubeaddons-catalog/values.yaml
Labels: chore, ready

#447 [chore] update catalog api server for kommander
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubeaddons-catalog-0.1.5.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.6.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
Labels: chore, ready

#451 kommander: Add cluster filter and # managed clusters to overview dashboard
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/dashboards/k8s-resources-clusters.yaml
Labels: ready

#455 fix: probe values under high load
  staging/dex-k8s-authenticator/Chart.yaml
  staging/dex-k8s-authenticator/templates/deployment.yaml
  staging/dex-k8s-authenticator/values.yaml
Labels: ready

#457 Allow nvidia driver to install with ami kernel
  staging/nvidia/Chart.yaml
  staging/nvidia/charts/nvidia-driver/Chart.yaml
  staging/nvidia/charts/nvidia-driver/templates/configmap.yaml
  staging/nvidia/charts/nvidia-driver/templates/daemonset.yaml
  staging/nvidia/requirements.yaml
Labels: ready

#458 fix: Add /private prefix for OSX docker mount
  Makefile
Labels: wip

#460 kommander: Fixes to the clusters summary dashboard
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/dashboards/k8s-resources-clusters.yaml
  stable/kommander/templates/grafana/hooks-home-dashboard.yaml
  stable/kommander/values.yaml
Labels: ready

#452 chore: Add testing instructions for Konvoy
  README.md
  TESTING.md
Labels: ready

#464 Revert "Add Dispatchfile"
  Dispatchfile
  test/e2e-kind.sh
  test/kind-config.yaml
Labels: bug, ready

#461 [Opsportal/kommander] Bump UI & KCL
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.7.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.8.tgz
  stable/kommander/charts/kommander-ui-2.30.3.tgz
  stable/kommander/charts/kommander-ui-2.35.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-2.30.3.tgz
  stable/opsportal/charts/kommander-ui-2.35.0.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#466 nvidia: Removed redundant vault repos.
  staging/nvidia/Chart.yaml
  staging/nvidia/charts/nvidia-driver/Chart.yaml
  staging/nvidia/charts/nvidia-driver/templates/configmap.yaml
  staging/nvidia/requirements.yaml
Labels: ready

#465 kommander: Port konvoy dashboards to centralized grafana
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/dashboards/apiserver.yaml
  stable/kommander/templates/grafana/dashboards/cluster-total.yaml
  stable/kommander/templates/grafana/dashboards/controller-manager.yaml
  stable/kommander/templates/grafana/dashboards/etcd.yaml
  stable/kommander/templates/grafana/dashboards/k8s-coredns.yaml
  stable/kommander/templates/grafana/dashboards/k8s-resources-cluster.yaml
  stable/kommander/templates/grafana/dashboards/k8s-resources-namespace.yaml
  stable/kommander/templates/grafana/dashboards/k8s-resources-node.yaml
  stable/kommander/templates/grafana/dashboards/k8s-resources-pod.yaml
  stable/kommander/templates/grafana/dashboards/k8s-resources-workload.yaml
  stable/kommander/templates/grafana/dashboards/k8s-resources-workloads-namespace.yaml
  stable/kommander/templates/grafana/dashboards/kubelet.yaml
  stable/kommander/templates/grafana/dashboards/namespace-by-pod.yaml
  stable/kommander/templates/grafana/dashboards/namespace-by-workload.yaml
  stable/kommander/templates/grafana/dashboards/node-cluster-rsrc-use.yaml
  stable/kommander/templates/grafana/dashboards/node-rsrc-use.yaml
  stable/kommander/templates/grafana/dashboards/nodes.yaml
  stable/kommander/templates/grafana/dashboards/pod-total.yaml
  stable/kommander/templates/grafana/dashboards/pods.yaml
  stable/kommander/templates/grafana/dashboards/prometheus-remote-write.yaml
  stable/kommander/templates/grafana/dashboards/prometheus.yaml
  stable/kommander/templates/grafana/dashboards/proxy.yaml
  stable/kommander/templates/grafana/dashboards/scheduler.yaml
  stable/kommander/templates/grafana/dashboards/statefulset.yaml
  stable/kommander/templates/grafana/dashboards/workload-total.yaml
  stable/kommander/values.yaml
Labels: ready

#472 [Kommander] kcl update to 0.4.10
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.10.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.9.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#473 [feature] add a chart for local-path-provisioner
  staging/local-path-provisioner/.helmignore
  staging/local-path-provisioner/Chart.yaml
  staging/local-path-provisioner/templates/_helpers.tpl
  staging/local-path-provisioner/templates/clusterrole.yaml
  staging/local-path-provisioner/templates/clusterrolebinding.yaml
  staging/local-path-provisioner/templates/configmap.yaml
  staging/local-path-provisioner/templates/deployment.yaml
  staging/local-path-provisioner/templates/post-install-job.yaml
  staging/local-path-provisioner/templates/serviceaccount.yaml
  staging/local-path-provisioner/templates/storageclass.yaml
  staging/local-path-provisioner/values.yaml
  test/ct-e2e.yaml
Labels: enhancement, ready

#482 chore: bump opsportal UI to v2.39.4
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-2.39.1.tgz
  stable/opsportal/charts/kommander-ui-2.39.4.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready
