Repository mesosphere/charts, pull requests merged in 2020-11, with the labels that each got.

#881 fix: bump dex-controller with a bugfix
  stable/dex/Chart.yaml
  stable/dex/charts/dex-controller-v0.6.4.tgz
  stable/dex/charts/dex-controller-v0.6.5.tgz
  stable/dex/requirements.lock
  stable/dex/requirements.yaml
Labels: bug, ready

#883 chore: bump yakcl to v0.6.5
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.6.4.tgz
  stable/kommander/charts/kommander-federation-v0.6.5.tgz
  stable/kommander/charts/kommander-licensing-v0.6.4.tgz
  stable/kommander/charts/kommander-licensing-v0.6.5.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#891 kommander: Fix cost analyzer ingress path
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: ready

#892 chore: Bump yakcl to v0.6.7
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.6.6.tgz
  stable/kommander/charts/kommander-federation-v0.6.7.tgz
  stable/kommander/charts/kommander-licensing-v0.6.6.tgz
  stable/kommander/charts/kommander-licensing-v0.6.7.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#894 create the serviceaccount needed for deletion jobs on delete
  stable/kommander/Chart.yaml
  stable/kommander/templates/hooks-roles.yaml
Labels: ready

#893 chore: Add --ignore-not-found to cm cleanup jobs
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/opsportal-username-secret.yaml
  stable/kommander/templates/kubecost/kubecost-query-stores-configmap.yaml
Labels: ready

#896 chore: bump yakcl to 0.6.8
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.6.7.tgz
  stable/kommander/charts/kommander-federation-v0.6.8.tgz
  stable/kommander/charts/kommander-licensing-v0.6.7.tgz
  stable/kommander/charts/kommander-licensing-v0.6.8.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: chore, ready

#897 kommander: Update yakcl to 0.6.9
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.6.8.tgz
  stable/kommander/charts/kommander-federation-v0.6.9.tgz
  stable/kommander/charts/kommander-licensing-v0.6.8.tgz
  stable/kommander/charts/kommander-licensing-v0.6.9.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#880 D2IQ-72789: move kubeaddons-kommander values into kommander chart
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: ready

#849 kubecost: Upgrade chart to 1.69.0
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.67.1.tgz
  stable/kubecost/charts/cost-analyzer-1.69.0.tgz
  stable/kubecost/requirements.lock
  stable/kubecost/requirements.yaml
Labels: ready

#904 kommander: Bump kubecost
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.1.15.tgz
  stable/kommander/charts/kubecost-0.3.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
Labels: ready

#890 Make GRPC and HTTP certificate creation non hook jobs.
  stable/dex/Chart.yaml
  stable/dex/templates/job-grpc-certs.yaml
  stable/dex/templates/job-web-certs.yaml
Labels: bug, ready

#906 feat(awsebscsiprovisioner): update aws-ebs-csi-driver
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/templates/_helpers.tpl
  stable/awsebscsiprovisioner/templates/roles.yaml
  stable/awsebscsiprovisioner/templates/statefulset.yaml
  stable/awsebscsiprovisioner/values.yaml
Labels: ready

#912 kommander: Fix wrong config block location
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: ready
