Repository mesosphere/charts, pull requests merged in 2020-08, with the labels that each got.

#711 chore: Misc. improvements to e2e-kind.sh
  Makefile
  test/e2e-kind.sh
Labels: ready

#721 [velero] fix: allow velero to deploy on helm2&3 without needing install hooks
  staging/velero/Chart.yaml
  staging/velero/crds/crds.yaml
  staging/velero/templates/backupstoragelocation.yaml
  staging/velero/templates/schedule.yaml
  staging/velero/templates/volumesnapshotlocation.yaml
Labels: ready

#722 kubecost: Upgrade base chart to v1.63.0
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.61.2.tgz
  stable/kubecost/charts/cost-analyzer-1.63.0.tgz
  stable/kubecost/requirements.lock
  stable/kubecost/requirements.yaml
Labels: ready

#726 [testing] chart-testing v3.0.0 and allow variable helm version for testing
  Makefile
  test/e2e-kind.sh
Labels: wip

#724 kommander: Update kubecost, decrease initial data lag
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.1.11.tgz
  stable/kommander/charts/kubecost-0.1.12.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
Labels: ready

#731 [azurediskprovisioner] fixing chart items/values that are broken
  stable/azurediskprovisioner/Chart.yaml
  stable/azurediskprovisioner/templates/storageclass.yaml
  stable/azurediskprovisioner/values.yaml
  test/e2e-kind.sh
Labels: ready

#729 [testing] chart-testing v3.0.0 and allow variable helm version for testing
  Dispatchfile
  Makefile
  test/e2e-kind.sh
Labels: ready

#732 [test] set ct version for helm2 correctly
  Makefile
Labels: ready

#734 [release/kommander-0.8.x] kommander: Update kubecost, decr initial data lag, decr loglevel
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.1.10.tgz
  stable/kommander/charts/kubecost-0.1.12.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/values.yaml
Labels: ready

#736 [gh-pages] Manually add and index kommander-0.8.43
  stable/index.yaml
  stable/kommander-0.8.43.tgz
Labels: ready

#733 [testing] additional changes to run tests separately, fix helm args
  Dispatchfile
  test/e2e-kind.sh
  test/helm2/ct-e2e.yaml
  test/helm2/ct.yaml
  test/helm3/ct-e2e.yaml
  test/helm3/ct.yaml
Labels: ready

#730 fix: only set CA data when necessary
  staging/dex-k8s-authenticator/Chart.yaml
  staging/dex-k8s-authenticator/html-templates/windows-tab.html
Labels: bug, ready

#737 [istio] crds directory created to support helm v3
  staging/istio/Chart.yaml
  staging/istio/crds/crd.yaml
Labels: ready

#738 [BUG] force `make publish` use helm2
  Makefile
Labels: ready

#740 Publish with helm v2 by setting explicitly
  Dispatchfile
Labels: ready

#742 [prometheus-operator] feat: add scripts to make upgrading easier
  staging/prometheus-operator/UPGRADING.md
  staging/prometheus-operator/patch/helpers.sh
  staging/prometheus-operator/patch/mesosphere/templates/grafana/cronjob-home-dashboard.yaml
  staging/prometheus-operator/patch/mesosphere/templates/grafana/dashboards/autoscalerdashboard.yaml
  staging/prometheus-operator/patch/mesosphere/templates/grafana/dashboards/calicodashboard.yaml
  staging/prometheus-operator/patch/mesosphere/templates/grafana/dashboards/elasticsearchdashboard.yaml
  staging/prometheus-operator/patch/mesosphere/templates/grafana/dashboards/fluentbitdashboard.yaml
  staging/prometheus-operator/patch/mesosphere/templates/grafana/dashboards/grafanadashboard.yaml
  staging/prometheus-operator/patch/mesosphere/templates/grafana/dashboards/kibanadashboard.yaml
  staging/prometheus-operator/patch/mesosphere/templates/grafana/dashboards/localvolumeprovisioner.yaml
  staging/prometheus-operator/patch/mesosphere/templates/grafana/dashboards/opsportaldashboard.yaml
  staging/prometheus-operator/patch/mesosphere/templates/grafana/dashboards/traefikdashboard.yaml
  staging/prometheus-operator/patch/mesosphere/templates/grafana/dashboards/velerodashboard.yaml
  staging/prometheus-operator/patch/mesosphere/templates/hooks/prometheus-cluster-id-hooks.yaml
  staging/prometheus-operator/patch/mesosphere/templates/ingress-rbac/alertmanager.yaml
  staging/prometheus-operator/patch/mesosphere/templates/ingress-rbac/grafana.yaml
  staging/prometheus-operator/patch/mesosphere/templates/ingress-rbac/prometheus.yaml
  staging/prometheus-operator/patch/mesosphere/templates/prometheus-operator/crds.yaml
  staging/prometheus-operator/patch/mesosphere/templates/rules/etcd-rules.yaml
  staging/prometheus-operator/patch/mesosphere/templates/rules/velero-rules.yaml
  staging/prometheus-operator/patch/patch.sh
  staging/prometheus-operator/patch/patch_1_mesosphere_dashboards.sh
  staging/prometheus-operator/patch/patch_2_mesosphere_cron_jobs.sh
  staging/prometheus-operator/patch/patch_3_mesosphere_hooks.sh
  staging/prometheus-operator/patch/patch_4_ingress_rbac.sh
  staging/prometheus-operator/patch/patch_50_prometheus_crd.sh
  staging/prometheus-operator/patch/patch_5_mesosphere_rules.sh
  staging/prometheus-operator/patch/patch_6_mesosphere_values.sh
  staging/prometheus-operator/patch/patch_7_prometheus_crd.sh
  staging/prometheus-operator/patch/patch_8_prometheus_operator_crd.sh
  staging/prometheus-operator/upgrade_operator.sh
Labels: ready

#747 fix: linting with v2.4.1 ct
  Dispatchfile
Labels: ready

#749 fix: lint requires ct.yaml to be in test dir
  Dispatchfile
  test/ct.yaml
Labels: ready

#744 test: Add retries to e2e test curls
  test/e2e-kind.sh
Labels: ready

#753 chore: Only add new files on publish of helm repo
  Makefile
Labels: chore, ready

#750 chore: bump kubeaddons-catalog image to v0.10.0
  staging/kubeaddons-catalog/Chart.yaml
  staging/kubeaddons-catalog/values.yaml
Labels: chore, ready

#755 [kommander] bump kubeaddons-catalog to 0.1.12
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubeaddons-catalog-0.1.11.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.12.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#756 [kommander] helm3 changes
  stable/kommander/Chart.yaml
  stable/kommander/charts/auto-provisioning-v0.3.0.tgz
  stable/kommander/charts/auto-provisioning-v0.4.1.tgz
  stable/kommander/charts/kommander-federation-v0.3.0.tgz
  stable/kommander/charts/kommander-federation-v0.4.1.tgz
  stable/kommander/charts/kommander-licensing-v0.3.0.tgz
  stable/kommander/charts/kommander-licensing-v0.4.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#758 Use 3.3.0 for publish
  Makefile
Labels: ready

#759 ensure helm is installed where it's executed
  Dispatchfile
  Makefile
Labels: ready

#754 chore: Only add new files on publish of helm repo
  Makefile
Labels: chore, ready

#760 chore: Fix up index yaml target deps
  Makefile
Labels: bug, chore, ready

#761 kommander: Update yakcl to v0.3.3
  stable/kommander/Chart.yaml
  stable/kommander/charts/auto-provisioning-v0.1.7.tgz
  stable/kommander/charts/auto-provisioning-v0.3.3.tgz
  stable/kommander/charts/kommander-federation-v0.1.7.tgz
  stable/kommander/charts/kommander-federation-v0.3.3.tgz
  stable/kommander/charts/kommander-licensing-v0.1.7.tgz
  stable/kommander/charts/kommander-licensing-v0.3.3.tgz
  stable/kommander/charts/kubecost-0.1.12.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#763 ensure we're using the correct helm
  Makefile
Labels: ready

#764 chore: bump yakcl deps
  stable/kommander/Chart.yaml
  stable/kommander/charts/auto-provisioning-v0.4.1.tgz
  stable/kommander/charts/auto-provisioning-v0.4.2.tgz
  stable/kommander/charts/kommander-federation-v0.4.1.tgz
  stable/kommander/charts/kommander-federation-v0.4.2.tgz
  stable/kommander/charts/kommander-licensing-v0.4.1.tgz
  stable/kommander/charts/kommander-licensing-v0.4.2.tgz
  stable/kommander/charts/kubeaddons-catalog-0.1.12.tgz
  stable/kommander/charts/kubecost-0.1.12.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#765 chore: Change dummylb timeout to 3mins
  test/e2e-kind.sh
Labels: Let me merge it, ready

#767 istio: Remove "kubernetes-service-monitor" service monitor
  staging/istio/Chart.yaml
  staging/istio/charts/prometheus-operator/templates/servicemonitors.yaml
Labels: ready

#770 chore: add service annotations
  stable/mtls-proxy/Chart.yaml
  stable/mtls-proxy/templates/service.yaml
Labels: ready
