Repository mesosphere/charts, pull requests merged in 2020-03, with the labels that each got.

#486 [prometheus-operator] fix: revert update that removed crds installation check.
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/prometheus-operator/crds.yaml
Labels: ready

#470 Readd Dispatchfile
  Dispatchfile
  test/e2e-kind.sh
  test/kind-config.yaml
Labels: question, ready

#488 fix: don't install packages as they're already installed
  Dispatchfile
Labels: do not merge, ready

#489 Workaround for PrometheusRuleFailures alert #D2IQ-65026
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/prometheus/rules-1.14/kube-apiserver-error.yaml
Labels: ready

#433 refactor: simplify kommander's grafana dashboard job
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/hooks-home-dashboard.yaml
Labels: enhancement, ready

#493 [opsportal/kommander] chore: bump ui
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-2.39.6.tgz
  stable/kommander/charts/kommander-ui-3.4.5.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-2.39.4.tgz
  stable/opsportal/charts/kommander-ui-3.4.5.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#495 traefik: allow extra entrypoints
  staging/traefik/Chart.yaml
  staging/traefik/README.md
  staging/traefik/templates/configmap.yaml
  staging/traefik/templates/service.yaml
  staging/traefik/values.yaml
Labels: ready

#496 cluster-autoscaler: initial commit
  stable/cluster-autoscaler/.helmignore
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/OWNERS
  stable/cluster-autoscaler/README.md
  stable/cluster-autoscaler/templates/NOTES.txt
  stable/cluster-autoscaler/templates/_helpers.tpl
  stable/cluster-autoscaler/templates/clusterrole.yaml
  stable/cluster-autoscaler/templates/clusterrolebinding.yaml
  stable/cluster-autoscaler/templates/deployment.yaml
  stable/cluster-autoscaler/templates/pdb.yaml
  stable/cluster-autoscaler/templates/podsecuritypolicy.yaml
  stable/cluster-autoscaler/templates/role.yaml
  stable/cluster-autoscaler/templates/rolebinding.yaml
  stable/cluster-autoscaler/templates/secret.yaml
  stable/cluster-autoscaler/templates/service.yaml
  stable/cluster-autoscaler/templates/serviceaccount.yaml
  stable/cluster-autoscaler/templates/servicemonitor.yaml
  stable/cluster-autoscaler/values.yaml
Labels: ready

#494 velero: cleanup velero minio
  staging/velero/Chart.yaml
  staging/velero/charts/minio/.helmignore
  staging/velero/charts/minio/Chart.yaml
  staging/velero/charts/minio/OWNERS
  staging/velero/charts/minio/PATCHES.md
  staging/velero/charts/minio/README.md
  staging/velero/charts/minio/ci/distributed-values.yaml
  staging/velero/charts/minio/patches/01-ingress-allow-empty-host-rule.patch
  staging/velero/charts/minio/patches/02-allow-upgrade-from-previous-version.patch
  staging/velero/charts/minio/templates/NOTES.txt
  staging/velero/charts/minio/templates/_helper_create_bucket.txt
  staging/velero/charts/minio/templates/_helpers.tpl
  staging/velero/charts/minio/templates/configmap.yaml
  staging/velero/charts/minio/templates/deployment.yaml
  staging/velero/charts/minio/templates/ingress.yaml
  staging/velero/charts/minio/templates/networkpolicy.yaml
  staging/velero/charts/minio/templates/poddisruptionbudget.yaml
  staging/velero/charts/minio/templates/post-install-create-bucket-job.yaml
  staging/velero/charts/minio/templates/pvc.yaml
  staging/velero/charts/minio/templates/secrets.yaml
  staging/velero/charts/minio/templates/service.yaml
  staging/velero/charts/minio/templates/serviceaccount.yaml
  staging/velero/charts/minio/templates/servicemonitor.yaml
  staging/velero/charts/minio/templates/statefulset.yaml
  staging/velero/charts/minio/values.yaml
  staging/velero/requirements.lock
  staging/velero/requirements.yaml
  staging/velero/templates/deployment.yaml
  staging/velero/templates/miniobackend.yaml
  staging/velero/values.yaml
Labels: ready

#497 kommander: bump ui chart to 3.6.1
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-3.4.5.tgz
  stable/kommander/charts/kommander-ui-3.6.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-3.4.5.tgz
  stable/opsportal/charts/kommander-ui-3.6.1.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#500 Update kommander and opsportal app versions
  stable/kommander/Chart.yaml
  stable/opsportal/Chart.yaml
Labels: ready

#498 velero-minio: merge upstream changes
  staging/velero/Chart.yaml
  staging/velero/charts/minio/Chart.yaml
  staging/velero/charts/minio/patches/01-ingress-allow-empty-host-rule.patch
  staging/velero/charts/minio/templates/deployment.yaml
  staging/velero/charts/minio/templates/statefulset.yaml
  staging/velero/charts/minio/values.yaml
  staging/velero/requirements.lock
  staging/velero/requirements.yaml
Labels: ready

#501 Update CODEOWNERS
  CODEOWNERS
Labels: ready

#502 chore: assign individual CODEOWNERS
  CODEOWNERS
Labels: do not merge, ready

#503 chore(kommander): bump kcl chart to 0.5.0
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.4.11.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#454 feat(cert-manager-setup): make certificates more customizable
  staging/cert-manager-setup/Chart.yaml
  staging/cert-manager-setup/README.md
  staging/cert-manager-setup/ci/general-test-values.yaml
  staging/cert-manager-setup/templates/certificates.yaml
  staging/cert-manager-setup/values.yaml
Labels: ready

#492 chore: update awsebscsiprovisioner chart
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/ci/annotations-kube2iam-usage.yaml
  stable/awsebscsiprovisioner/ci/more-specific-settings.yaml
  stable/awsebscsiprovisioner/templates/_helpers.tpl
  stable/awsebscsiprovisioner/templates/csidriver.yaml
  stable/awsebscsiprovisioner/templates/daemonset.yaml
  stable/awsebscsiprovisioner/templates/roles.yaml
  stable/awsebscsiprovisioner/templates/statefulset-snapshot-controller.yaml
  stable/awsebscsiprovisioner/templates/statefulset.yaml
  stable/awsebscsiprovisioner/templates/storageclass.yaml
  stable/awsebscsiprovisioner/values.yaml
  test/ct-e2e.yaml
  test/e2e-kind.sh
Labels: ready

#453 refactor(kommander): Use thanos & karma source code as subcharts
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma-0.3.8.tgz
  stable/kommander/charts/kommander-karma/.helmignore
  stable/kommander/charts/kommander-karma/Chart.yaml
  stable/kommander/charts/kommander-karma/README.md
  stable/kommander/charts/kommander-karma/charts/karma-1.4.0.tgz
  stable/kommander/charts/kommander-karma/requirements.lock
  stable/kommander/charts/kommander-karma/requirements.yaml
  stable/kommander/charts/kommander-karma/templates/_helpers.tpl
  stable/kommander/charts/kommander-karma/templates/cleanup-configmap.yaml
  stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
  stable/kommander/charts/kommander-karma/templates/secret.yaml
  stable/kommander/charts/kommander-karma/values.yaml
  stable/kommander/charts/kommander-thanos-0.1.13.tgz
  stable/kommander/charts/kommander-thanos/.helmignore
  stable/kommander/charts/kommander-thanos/Chart.yaml
  stable/kommander/charts/kommander-thanos/README.md
  stable/kommander/charts/kommander-thanos/charts/thanos-0.3.9.tgz
  stable/kommander/charts/kommander-thanos/requirements.lock
  stable/kommander/charts/kommander-thanos/requirements.yaml
  stable/kommander/charts/kommander-thanos/templates/_helpers.tpl
  stable/kommander/charts/kommander-thanos/templates/federated-addon.yaml
  stable/kommander/charts/kommander-thanos/templates/query-stores-configmap.yaml
  stable/kommander/charts/kommander-thanos/templates/secret.yaml
  stable/kommander/charts/kommander-thanos/values.yaml
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#506 chore: Delete kommander-thanos and kommander-karma charts
  stable/kommander-karma/.helmignore
  stable/kommander-karma/Chart.yaml
  stable/kommander-karma/README.md
  stable/kommander-karma/charts/karma-1.4.0.tgz
  stable/kommander-karma/requirements.lock
  stable/kommander-karma/requirements.yaml
  stable/kommander-karma/templates/_helpers.tpl
  stable/kommander-karma/templates/cleanup-configmap.yaml
  stable/kommander-karma/templates/federated-addon.yaml
  stable/kommander-karma/templates/ingress-roles.yaml
  stable/kommander-karma/templates/secret.yaml
  stable/kommander-karma/values.yaml
  stable/kommander-thanos/.helmignore
  stable/kommander-thanos/Chart.yaml
  stable/kommander-thanos/README.md
  stable/kommander-thanos/charts/thanos-0.3.9.tgz
  stable/kommander-thanos/requirements.lock
  stable/kommander-thanos/requirements.yaml
  stable/kommander-thanos/templates/_helpers.tpl
  stable/kommander-thanos/templates/federated-addon.yaml
  stable/kommander-thanos/templates/ingress-roles.yaml
  stable/kommander-thanos/templates/query-stores-configmap.yaml
  stable/kommander-thanos/templates/secret.yaml
  stable/kommander-thanos/values.yaml
Labels: chore, ready

#507 feat(kube-oidc-proxy): added caSystemDefault and caCertPemHostPath
  staging/kube-oidc-proxy/Chart.yaml
  staging/kube-oidc-proxy/templates/deployment.yaml
  staging/kube-oidc-proxy/values.yaml
Labels: ready

#519 [kommander] bump UI & KCL
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.0.tgz
  stable/kommander/charts/kommander-cluster-lifecycle-v0.5.1.tgz
  stable/kommander/charts/kommander-ui-3.12.3.tgz
  stable/kommander/charts/kommander-ui-3.16.5.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#515 [kommander] Revert "chore: move values from addon to chart"
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
Labels: ready

#520 [opsportal] chore: bump opsportal ui 3.6.1 -> 3.16.5
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-3.16.5.tgz
  stable/opsportal/charts/kommander-ui-3.6.1.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#505 fix: Dispatch publish tasks
  Dispatchfile
Labels: ready

#522 fix: grafana dashboard job only if defaultDashboardsEnabled
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/mesosphere-hooks/grafana-default-dashboard-hook.yaml
Labels: ready

#517 [prometheus-operator] fix: hook should not call static service name
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/hooks-home-dashboard.yaml
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/mesosphere-hooks/grafana-default-dashboard-hook.yaml
  staging/prometheus-operator/values.yaml
Labels: ready

#518 [traefik] fix: set image pull policy to IfNotPresent
  staging/traefik/Chart.yaml
  staging/traefik/templates/deployment.yaml
  staging/traefik/values.yaml
Labels: ready

#521 missing volumesnapshots/status permission
  stable/awsebscsiprovisioner/Chart.yaml
  stable/awsebscsiprovisioner/templates/roles.yaml
Labels: ready

#527 velero-minio: fix the data loss issue
  staging/velero/Chart.yaml
  staging/velero/charts/minio/templates/cleanup-job.yaml
Labels: bug, ready

#508 chore: azurecsi driver version bump
  stable/azuredisk-csi-driver/Chart.yaml
  stable/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
  stable/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
  stable/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
  stable/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
  stable/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
  stable/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
  stable/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
  stable/azuredisk-csi-driver/values.yaml
Labels: ready

#528 Disable Ingress by default as discussed per D2IQ-64149
  staging/kubeaddons-catalog/Chart.yaml
  staging/kubeaddons-catalog/values.yaml
Labels: ready

#530 bug: fix misplaced quotes
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/mesosphere-hooks/grafana-default-dashboard-hook.yaml
Labels: bug, ready

#524 knative: Added requirements.yaml and enable/disable switches to knative
  staging/knative/Chart.yaml
  staging/knative/charts/serving/Chart.yaml
  staging/knative/charts/serving/templates/custom-metrics-apiservice.yaml
  staging/knative/charts/serving/templates/gateway.yaml
  staging/knative/charts/serving/templates/namespace.yaml
  staging/knative/charts/serving/values.yaml
  staging/knative/requirements.yaml
  staging/knative/values.yaml
Labels: ready

#531 bug: make configmap name match reference
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/templates/mesosphere-hooks/grafana-default-dashboard-hook.yaml
Labels: ready

#532 fix: add permissions to handle konvoycluster resources
  stable/cluster-autoscaler/Chart.yaml
  stable/cluster-autoscaler/templates/clusterrole.yaml
Labels: bug, ready
