Repository mesosphere/charts, pull requests merged in 2021-02, with the labels that each got.

#970 [release/prometheus-operator-9.3.x] fix images (cve)
  Makefile
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/patch/mesosphere/templates/grafana/cronjob-home-dashboard.yaml
  staging/prometheus-operator/patch/patch_6_mesosphere_values.sh
  staging/prometheus-operator/values.yaml
  test/ct.yaml
  test/e2e-kind.sh
  test/helm2/ct-e2e.yaml
  test/helm2/ct.yaml
  test/helm3/ct-e2e.yaml
  test/helm3/ct.yaml
Labels: ready

#973 chore: bump opsportal/kommander ui to 6.84.2
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-6.84.1.tgz
  stable/kommander/charts/kommander-ui-6.84.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-6.84.1.tgz
  stable/opsportal/charts/kommander-ui-6.84.2.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#974 kommander: Update yakcl to v0.8.3
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.8.2.tgz
  stable/kommander/charts/kommander-federation-v0.8.3.tgz
  stable/kommander/charts/kommander-licensing-v0.8.2.tgz
  stable/kommander/charts/kommander-licensing-v0.8.3.tgz
  stable/kommander/charts/kubecost-0.5.1.tgz
  stable/kommander/charts/kubecost-0.5.2.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#969 prometheus: update jq images
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/patch/patch_6_mesosphere_values.sh
  staging/prometheus-operator/values.yaml
Labels: ready

#977 chore: use /bin/sh in kommander-set-grafana job
  stable/kommander/Chart.yaml
  stable/kommander/templates/grafana/cronjob-home-dashboard.yaml
Labels: bug, ready

#965 chore: Bump kubecost to 1.73.0
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.71.1.tgz
  stable/kubecost/charts/cost-analyzer-1.73.0.tgz
  stable/kubecost/requirements.lock
  stable/kubecost/requirements.yaml
  stable/kubecost/values.yaml
Labels: ready

#978 kommander: Bump kubecost
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.5.2.tgz
  stable/kommander/charts/kubecost-0.6.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#980 chore: Bump k8s-sidecar to 1.3.0 to align and fix CVEs
  stable/grafana/Chart.yaml
  stable/grafana/values.yaml
  stable/kommander/Chart.yaml
  stable/kommander/values.yaml
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/values.yaml
Labels: ready

#981 chore: Bump kubecost grafana sidecar image to fix cve
  stable/kubecost/Chart.yaml
  stable/kubecost/values.yaml
Labels: ready

#982 chore: Bump kubecost in kommander
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.6.0.tgz
  stable/kommander/charts/kubecost-0.6.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#983 chore: bump kommander/opsportal ui to 6.84.3
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-6.84.2.tgz
  stable/kommander/charts/kommander-ui-6.84.3.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-6.84.2.tgz
  stable/opsportal/charts/kommander-ui-6.84.3.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#984 kommander: Bump yakcl to v0.8.4
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.8.3.tgz
  stable/kommander/charts/kommander-federation-v0.8.4.tgz
  stable/kommander/charts/kommander-licensing-v0.8.3.tgz
  stable/kommander/charts/kommander-licensing-v0.8.4.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#988 [release/kubecost-0.5.x] kubecost: Bump grafana sidecar image
  stable/kubecost/Chart.yaml
  stable/kubecost/values.yaml
Labels: ready

#989 kommander: Downgrade kubecost to v0.5.3
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.8.4.tgz
  stable/kommander/charts/kommander-federation-v0.8.5.tgz
  stable/kommander/charts/kommander-licensing-v0.8.4.tgz
  stable/kommander/charts/kommander-licensing-v0.8.5.tgz
  stable/kommander/charts/kubecost-0.5.3.tgz
  stable/kommander/charts/kubecost-0.6.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#990 kommander: Update yakcl to v0.8.6
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.8.5.tgz
  stable/kommander/charts/kommander-federation-v0.8.6.tgz
  stable/kommander/charts/kommander-licensing-v0.8.5.tgz
  stable/kommander/charts/kommander-licensing-v0.8.6.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#993 prometheus: Add missing pre-delete hook to SA
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/patch/mesosphere/templates/hooks/prometheus-cluster-id-hooks.yaml
  staging/prometheus-operator/templates/mesosphere-hooks/prometheus-cluster-id-hooks.yaml
Labels: ready

#994 [release/prometheus-operator-9.3.x] Add missing pre-delete hook to SA
  staging/prometheus-operator/Chart.yaml
  staging/prometheus-operator/patch/mesosphere/templates/hooks/prometheus-cluster-id-hooks.yaml
  staging/prometheus-operator/templates/mesosphere-hooks/prometheus-cluster-id-hooks.yaml
Labels: ready

#1000 kubecost: Use --ignore-not-found in kubectl delete
  stable/kubecost/Chart.yaml
  stable/kubecost/templates/hooks-clusterid.yaml
Labels: ready

#999 [release/kubecost-0.5.x] fix: Use --ignore-not-found in kubectl delete
  stable/kubecost/Chart.yaml
  stable/kubecost/templates/hooks-clusterid.yaml
Labels: ready

#996 kommander: add before-hook-creation delete annotations to hook jobs
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.5.3.tgz
  stable/kommander/charts/kubecost-0.5.4.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/grafana/opsportal-username-secret.yaml
  stable/kommander/templates/kubecost/kubecost-query-stores-configmap.yaml
Labels: ready

#997 [release/kommander-0.12.x] kommander: add before-hook-creation delete annotations to hook jobs
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma/templates/cleanup-configmap.yaml
  stable/kommander/charts/kommander-thanos/templates/query-stores-configmap.yaml
  stable/kommander/charts/kubecost-0.5.1.tgz
  stable/kommander/charts/kubecost-0.5.4.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/grafana/opsportal-username-secret.yaml
  stable/kommander/templates/kubecost/kubecost-query-stores-configmap.yaml
Labels: ready

#1001 [release/kubecost-0.1.x] fix: Use --ignore-not-found in kubectl delete
  stable/kubecost/Chart.yaml
  stable/kubecost/templates/hooks-clusterid.yaml
Labels: ready

#998 [release/kommander-0.8.x] kommander: add before-hook-creation delete annotations to hook jobs
  .gitignore
  Dispatchfile
  Makefile
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma/templates/cleanup-configmap.yaml
  stable/kommander/charts/kommander-thanos/templates/query-stores-configmap.yaml
  stable/kommander/charts/kubecost-0.1.12.tgz
  stable/kommander/charts/kubecost-0.1.16.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/grafana/opsportal-username-secret.yaml
  stable/kommander/templates/kubecost/kubecost-query-stores-configmap.yaml
Labels: ready

#1002 kommander / opsportal: Bump kommander-ui to 6.85.1
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-6.84.3.tgz
  stable/kommander/charts/kommander-ui-6.85.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-6.84.3.tgz
  stable/opsportal/charts/kommander-ui-6.85.1.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#971 [kibana] chart docs to explain deviation from upstream.
  stable/kibana/Chart.yaml
  stable/kibana/README.md
Labels: ready

#992 kubecost: Bump kubecost to v1.74.0
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.73.0.tgz
  stable/kubecost/charts/cost-analyzer-1.74.0.tgz
  stable/kubecost/requirements.lock
  stable/kubecost/requirements.yaml
  stable/kubecost/values.yaml
Labels: ready

#1004 kommander / opsportal: Bump kommander-ui to 6.88.0
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-6.85.1.tgz
  stable/kommander/charts/kommander-ui-6.88.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-6.85.1.tgz
  stable/opsportal/charts/kommander-ui-6.88.0.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#991 kommander: Bump kommander to 0.16.0 following v1.3.0 release
  stable/kommander/Chart.yaml
  stable/kommander/README.md
Labels: Let me merge it, ready

#1009 kommander: Bump yakcl to 0.9.0
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.8.6.tgz
  stable/kommander/charts/kommander-federation-v0.9.0.tgz
  stable/kommander/charts/kommander-licensing-v0.8.6.tgz
  stable/kommander/charts/kommander-licensing-v0.9.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#1005 kubecost: Bump kubecost to v1.75.1
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.74.0.tgz
  stable/kubecost/charts/cost-analyzer-1.75.1.tgz
  stable/kubecost/requirements.lock
  stable/kubecost/requirements.yaml
  stable/kubecost/values.yaml
Labels: ready

#1010 kommander: Bump kubecost to 0.7.0
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.5.4.tgz
  stable/kommander/charts/kubecost-0.7.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready
