Repository mesosphere/charts, pull requests merged in 2021-03, with the labels that each got.

#1013 [gatekeeper] chore: allow exclusion of namespaces in chart
  staging/gatekeeper/Chart.yaml
  staging/gatekeeper/patch/patch_1_mesosphere_values.sh
  staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml
  staging/gatekeeper/values.yaml
Labels: ready

#1017 [gatekeeper] chore: change scope of proxy items as wildcard does not work consistently
  staging/gatekeeper/Chart.yaml
  staging/gatekeeper/patch/templates/gatekeeper-proxy-mutations.yaml
  staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml
Labels: ready

#1019 [gatekeeper] chore: allow namespace selector for mutations
  staging/gatekeeper/Chart.yaml
  staging/gatekeeper/patch/templates/gatekeeper-proxy-mutations.yaml
  staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml
  staging/gatekeeper/values.yaml
Labels: ready

#1021 [kommander] chore: allow adding labels to kommander namespace
  stable/kommander/Chart.yaml
  stable/kommander/templates/namespace-labeler.yaml
  stable/kommander/values.yaml
Labels: ready

#1023 [release/kommander-0.15.x] Bump yakcl to v0.8.7
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.8.6.tgz
  stable/kommander/charts/kommander-federation-v0.8.7.tgz
  stable/kommander/charts/kommander-licensing-v0.8.6.tgz
  stable/kommander/charts/kommander-licensing-v0.8.7.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#1022 bug: update kommander-ui dep for opsportal
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-6.88.0.tgz
  stable/kommander/charts/kommander-ui-6.90.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-6.88.0.tgz
  stable/opsportal/charts/kommander-ui-6.90.1.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#1026 [release/kommander 0.15.x] backport: Bump kommander-ui (bug fixes)
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-6.88.0.tgz
  stable/kommander/charts/kommander-ui-6.91.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#1029 chore: fix gatekeeper so only proxy settings are for mutations
  staging/gatekeeper/Chart.yaml
  staging/gatekeeper/patch/templates/gatekeeper-proxy-mutations.yaml
  staging/gatekeeper/templates/gatekeeper-audit-deployment.yaml
  staging/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
  staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml
  staging/gatekeeper/values.yaml
Labels: ready

#1025 bug: update opsportal & kommander to ui v6.91.1
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-ui-6.90.1.tgz
  stable/kommander/charts/kommander-ui-6.91.1.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/opsportal/Chart.yaml
  stable/opsportal/charts/kommander-ui-6.90.1.tgz
  stable/opsportal/charts/kommander-ui-6.91.1.tgz
  stable/opsportal/requirements.lock
  stable/opsportal/requirements.yaml
Labels: ready

#1020 fix: make resource purging faster
  stable/kommander/Chart.yaml
  stable/kommander/templates/pre-deletion-purger.yaml
Labels: bug, ready

#1030 chore: change scope of mutations since we use namespaceselector
  staging/gatekeeper/Chart.yaml
  staging/gatekeeper/patch/templates/gatekeeper-proxy-mutations.yaml
  staging/gatekeeper/templates/gatekeeper-proxy-mutations.yaml
Labels: ready

#1032 chore: batch requirements 0.10.0
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.10.0.tgz
  stable/kommander/charts/kommander-federation-v0.9.0.tgz
  stable/kommander/charts/kommander-licensing-v0.10.0.tgz
  stable/kommander/charts/kommander-licensing-v0.9.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#1036 chore: add kubefed fork
  staging/kubefed/Chart.yaml
  staging/kubefed/README.md
  staging/kubefed/charts/controllermanager/Chart.yaml
  staging/kubefed/charts/controllermanager/crds/crds.yaml
  staging/kubefed/charts/controllermanager/templates/_helpers.tpl
  staging/kubefed/charts/controllermanager/templates/aggregate_clusterroles.yaml
  staging/kubefed/charts/controllermanager/templates/clusterrole.yaml
  staging/kubefed/charts/controllermanager/templates/clusterrolebindings.yaml
  staging/kubefed/charts/controllermanager/templates/deployments.yaml
  staging/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  staging/kubefed/charts/controllermanager/templates/rolebindings.yaml
  staging/kubefed/charts/controllermanager/templates/roles.yaml
  staging/kubefed/charts/controllermanager/templates/service.yaml
  staging/kubefed/charts/controllermanager/templates/serviceaccounts.yaml
  staging/kubefed/charts/controllermanager/templates/webhook.yaml
  staging/kubefed/crds/crds.yaml
  staging/kubefed/templates/_helpers.tpl
  staging/kubefed/templates/federatedtypeconfig.yaml
  staging/kubefed/values.yaml
  test/ct.yaml
  test/helm2/ct-e2e.yaml
  test/helm2/ct.yaml
  test/helm3/ct-e2e.yaml
  test/helm3/ct.yaml
Labels: ready

#1048 [kommander] feat: use custom built karma version with proxy support
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma/Chart.yaml
  stable/kommander/charts/kommander-karma/values.yaml
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#1054 feat: check connection-type label where necessary
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma/Chart.yaml
  stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
  stable/kommander/charts/kommander-thanos/Chart.yaml
  stable/kommander/charts/kommander-thanos/templates/federated-addon.yaml
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/kubecost/federated-addon.yaml
Labels: Let me merge it

#1055 [mtls-proxy] feat: add custom env variables support
  stable/mtls-proxy/Chart.yaml
  stable/mtls-proxy/templates/deployment.yaml
  stable/mtls-proxy/values.yaml
Labels: ready

#1037 chore: Bump kubecost to 1.76.0
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.75.1.tgz
  stable/kubecost/charts/cost-analyzer-1.76.0.tgz
  stable/kubecost/requirements.lock
  stable/kubecost/requirements.yaml
Labels: ready

#1057 [kommander] feat: create local secrets with server proxy certificates
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma/Chart.yaml
  stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
  stable/kommander/charts/kommander-thanos/Chart.yaml
  stable/kommander/charts/kommander-thanos/templates/secret.yaml
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/kubecost/secret.yaml
Labels: ready

#1062 [mtls-proxy] fix: env values indentation
  stable/mtls-proxy/Chart.yaml
  stable/mtls-proxy/templates/deployment.yaml
  stable/mtls-proxy/values.yaml
Labels: ready

#1059 kommander: Bump kubecost
  stable/kommander/Chart.yaml
  stable/kommander/charts/kubecost-0.7.0.tgz
  stable/kommander/charts/kubecost-0.8.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#1064 kommander: Bump yakcl to v0.11.0 and ui to 6.92.0
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.10.0.tgz
  stable/kommander/charts/kommander-federation-v0.11.0.tgz
  stable/kommander/charts/kommander-licensing-v0.10.0.tgz
  stable/kommander/charts/kommander-licensing-v0.11.0.tgz
  stable/kommander/charts/kommander-ui-6.91.1.tgz
  stable/kommander/charts/kommander-ui-6.92.0.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#1068 bump dummylb which updated the k8s libraries to 0.20.5
  test/e2e-kind.sh
Labels: ready

#1071 [kommander] chore: bump mtls-proxy version in kommander
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma/Chart.yaml
  stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
  stable/kommander/charts/kommander-thanos/Chart.yaml
  stable/kommander/charts/kommander-thanos/templates/federated-addon.yaml
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/kubecost/federated-addon.yaml
Labels: ready

#1070 [release/kommander-0.15.x] chore: Bump yakcl to 0.8.9
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-federation-v0.8.8.tgz
  stable/kommander/charts/kommander-federation-v0.8.9.tgz
  stable/kommander/charts/kommander-licensing-v0.8.8.tgz
  stable/kommander/charts/kommander-licensing-v0.8.9.tgz
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
Labels: ready

#1076 [joe/promup] prom patch to ignore new crd fields
  staging/prometheus-operator/.helmignore
  staging/prometheus-operator/files/crds.yaml
  staging/prometheus-operator/patch/mesosphere/patch/12_conditional_avoid_broken_crd.patch
  staging/prometheus-operator/patch/patch_12_avoid_broken_crd.sh
  staging/prometheus-operator/patch/patch_12_mesosphere_patch_avoid_broken_crd.sh
  staging/prometheus-operator/patch/patch_6_mesosphere_values.sh
  staging/prometheus-operator/patch/patch_7_mesosphere_default_values.sh
  staging/prometheus-operator/patch/patch_9_mesosphere_helmignore.sh
  staging/prometheus-operator/templates/alertmanager/alertmanager.yaml
  staging/prometheus-operator/templates/install_crds.yaml
  staging/prometheus-operator/templates/prometheus/prometheus.yaml
  staging/prometheus-operator/values.yaml
Labels: wip

#1079 [mtls-proxy] [kommander] fix ghosttunnel tag
  stable/kommander/Chart.yaml
  stable/kommander/charts/kommander-karma/Chart.yaml
  stable/kommander/charts/kommander-karma/templates/federated-addon.yaml
  stable/kommander/charts/kommander-thanos/Chart.yaml
  stable/kommander/charts/kommander-thanos/templates/federated-addon.yaml
  stable/kommander/requirements.lock
  stable/kommander/requirements.yaml
  stable/kommander/templates/kubecost/federated-addon.yaml
  stable/mtls-proxy/Chart.yaml
  stable/mtls-proxy/values.yaml
Labels: ready
