Repository mesosphere/charts, pull requests merged in 2022-10, with the labels that each got.

#1356 feat: standalone chart for ObjectBucketClaim
  stable/object-bucket-claim/.helmignore
  stable/object-bucket-claim/Chart.yaml
  stable/object-bucket-claim/README.md
  stable/object-bucket-claim/templates/_helpers.tpl
  stable/object-bucket-claim/templates/object-bucket-claim.yaml
  stable/object-bucket-claim/values.yaml
  test/helm3/ct-e2e.yaml
  test/helm3/ct.yaml
Labels: ready, ok-to-test

#1358 feat: Add Postgres Operator from CrunchyData
  staging/postgres-cluster/Chart.yaml
  staging/postgres-cluster/templates/NOTES.txt
  staging/postgres-cluster/templates/_azure.tpl
  staging/postgres-cluster/templates/_gcs.tpl
  staging/postgres-cluster/templates/_s3.tpl
  staging/postgres-cluster/templates/pgbackrest-secret.yaml
  staging/postgres-cluster/templates/postgres.yaml
  staging/postgres-cluster/values.yaml
  staging/postgres-operator/.gitattributes
  staging/postgres-operator/.helmignore
  staging/postgres-operator/Chart.yaml
  staging/postgres-operator/crds/postgres-operator.crunchydata.com_pgupgrades.yaml
  staging/postgres-operator/crds/postgres-operator.crunchydata.com_postgresclusters.yaml
  staging/postgres-operator/templates/NOTES.txt
  staging/postgres-operator/templates/_helpers.tpl
  staging/postgres-operator/templates/manager-upgrade.yaml
  staging/postgres-operator/templates/manager.yaml
  staging/postgres-operator/templates/role-upgrade.yaml
  staging/postgres-operator/templates/role.yaml
  staging/postgres-operator/templates/role_binding.yaml
  staging/postgres-operator/templates/service_account.yaml
  staging/postgres-operator/values.yaml
  test/helm3/ct-e2e.yaml
Labels: ready, ok-to-test

#1359 feat: local-path-provisioner v0.0.22
  staging/local-path-provisioner/Chart.yaml
  staging/local-path-provisioner/README.md
  staging/local-path-provisioner/templates/NOTES.txt
  staging/local-path-provisioner/templates/_helpers.tpl
  staging/local-path-provisioner/templates/clusterrole.yaml
  staging/local-path-provisioner/templates/clusterrolebinding.yaml
  staging/local-path-provisioner/templates/configmap.yaml
  staging/local-path-provisioner/templates/deployment.yaml
  staging/local-path-provisioner/templates/post-install-job.yaml
  staging/local-path-provisioner/templates/registry-secret.yaml
  staging/local-path-provisioner/templates/serviceaccount.yaml
  staging/local-path-provisioner/templates/storageclass.yaml
  staging/local-path-provisioner/values.yaml
Labels: ready, ok-to-test

#1357 feat: Bump cert-manager crds to 1.9.1
  stable/cert-manager-crds/Chart.yaml
  stable/cert-manager-crds/Makefile
  stable/cert-manager-crds/crds/cert-manager.crds.yaml
Labels: ready, ok-to-test

#1361 chore: switch to use role
  stable/object-bucket-claim/Chart.yaml
  stable/object-bucket-claim/templates/object-bucket-claim.yaml
Labels: ready, ok-to-test

#1362 chore: remove defaults
  stable/object-bucket-claim/Chart.yaml
  stable/object-bucket-claim/values.yaml
Labels: ready, ok-to-test

#1363 fix: handle helm deadlock
  stable/object-bucket-claim/Chart.yaml
  stable/object-bucket-claim/templates/object-bucket-claim.yaml
Labels: ready, ok-to-test

#1364 feat: Bump kubecost to 1.97.0
  stable/kubecost/Chart.lock
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.96.0.tgz
  stable/kubecost/charts/cost-analyzer-1.97.0.tgz
Labels: ready, ok-to-test

#1365 ci: add stacked PR support
  .github/workflows/stacked-prs.yml
Labels: ready, ok-to-test

#1366 chore: add git ignore .idea/ directory
  .gitignore
Labels: ready, ok-to-test

#1368 ci: delete dispatch file [D2IQ-93788]
  Dispatchfile
Labels: ready, ok-to-test

#1369 refactor: lint makefile variables
  Makefile
Labels: ready, chore

#1370 chore: add help target to Makefile
  Makefile
Labels: ready, chore

#1371 chore: add some make execution logs
  Makefile
Labels: ready, chore

#1373 ci: add dev workflow
  .github/workflows/ct.yaml
Labels: ready, chore

#1374 ci: add publish charts workflow
  .github/workflows/publish.yml
  Makefile
  hack/charts/publish.sh
Labels: ready

#1375 fix: adjust tool version handling for GHA worflows
  .github/workflows/publish.yml
  Makefile
Labels: ready, ok-to-test

#1378 chore: add .local dir to gitignore
  .gitignore
Labels: ready, chore

#1379 feat: Bump istio to 1.15.3
  staging/istio/README.md
  staging/istio/charts/grafana/dashboards/istio-extension-dashboard.json
  staging/istio/charts/grafana/dashboards/istio-service-dashboard.json
  staging/istio/templates/clusterrole_binding.yaml
  staging/istio/templates/crds.yaml
  staging/istio/templates/service_account.yaml
  staging/istio/values.yaml
Labels: ready, ok-to-test

#1380 feat: Bump istio chart version
  staging/istio/Chart.yaml
Labels: ready, ok-to-test
