Repository mesosphere/charts, pull requests merged in 2022-05, with the labels that each got.

#1321 chore: bump dex
  stable/dex/Chart.yaml
  stable/dex/charts/dex-controller-v0.6.16.tgz
  stable/dex/charts/dex-controller-v0.6.17.tgz
  stable/dex/requirements.lock
  stable/dex/requirements.yaml
Labels: ready, ok-to-test

#1322 2.2.1 backport for grafana view permission fix
  staging/kube-prometheus-stack/Chart.yaml
  staging/kube-prometheus-stack/patch/mesosphere/templates/ingress-rbac/grafana.yaml
  staging/kube-prometheus-stack/templates/ingress-rbac/grafana.yaml
Labels: ready

#1328 fix: use mhrabovcin/dummylb container
  test/e2e-kind.sh
Labels: ok-to-test
