Repository mesosphere/charts, pull requests merged in 2023-09, with the labels that each got.

#1449 fix: add required flag to be able to view grafana dashboard
  staging/kube-prometheus-stack/Chart.lock
  staging/kube-prometheus-stack/Chart.yaml
  staging/kube-prometheus-stack/charts/grafana-6.57.1.tgz
  staging/kube-prometheus-stack/charts/grafana-6.57.4.tgz
  staging/kube-prometheus-stack/patch/mesosphere/templates/ingress-rbac/grafana.yaml
  staging/kube-prometheus-stack/templates/ingress-rbac/grafana.yaml
Labels: ready, ok-to-test

#1450 ci(publish): Run on pushes to release branches
  .github/workflows/publish.yml
  CONTRIBUTING.md
Labels: documentation, ready, ok-to-test

#1452 fix: add required flag to be able to view grafana dashboard
  staging/kube-prometheus-stack/Chart.yaml
  staging/kube-prometheus-stack/patch/mesosphere/templates/ingress-rbac/grafana.yaml
  staging/kube-prometheus-stack/templates/ingress-rbac/grafana.yaml
Labels: ready, ok-to-test

#1451 fix: add required flag to be able to view grafana dashboard
  staging/kube-prometheus-stack/Chart.yaml
  staging/kube-prometheus-stack/patch/mesosphere/templates/ingress-rbac/grafana.yaml
  staging/kube-prometheus-stack/templates/ingress-rbac/grafana.yaml
Labels: ready, ok-to-test

#1453 feat(kubecost): Bump to upstream 1.106.0
  stable/kubecost/Chart.lock
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.105.2.tgz
  stable/kubecost/charts/cost-analyzer-1.106.0.tgz
Labels: ready, ok-to-test

#1454 chore: bumps dex-controller to v0.9.1
  stable/dex/Chart.yaml
  stable/dex/charts/dex-controller-v0.8.3.tgz
  stable/dex/charts/dex-controller-v0.9.1.tgz
  stable/dex/requirements.lock
  stable/dex/requirements.yaml
Labels: ready, chore, ok-to-test

#1455 feat: bump cert-manager to v1.12.3
  stable/cert-manager-crds/Chart.yaml
  stable/cert-manager-crds/Makefile
  stable/cert-manager-crds/crds/cert-manager.crds.yaml
Labels: ready
