Repository mesosphere/charts, pull requests merged in 2023-04, with the labels that each got.

#1405 feat: Bump istio to 1.17.1
  staging/istio/Chart.yaml
  staging/istio/files/gen-operator.yaml
  staging/istio/patch/patches/1_values.patch
  staging/istio/templates/deployment.yaml
  staging/istio/upgrade_operator.sh
  staging/istio/values.yaml
Labels: ready, ok-to-test

#1409 feat: Add priority class support to TFA
  staging/traefik-forward-auth/Chart.yaml
  staging/traefik-forward-auth/templates/deployment.yaml
  staging/traefik-forward-auth/values.yaml
Labels: ready, ok-to-test

#1410 feat: Add priority class support to karma
  stable/karma/Chart.yaml
  stable/karma/templates/deployment.yaml
  stable/karma/values.yaml
Labels: ready, ok-to-test

#1411 feat: Add priority class support to DKA
  staging/dex-k8s-authenticator/Chart.yaml
  staging/dex-k8s-authenticator/templates/deployment.yaml
  staging/dex-k8s-authenticator/values.yaml
Labels: ready, ok-to-test

#1412 feat: Add priority class support to dex
  stable/dex/Chart.yaml
  stable/dex/charts/dex-controller-v0.8.0.tgz
  stable/dex/charts/dex-controller-v0.8.1.tgz
  stable/dex/requirements.lock
  stable/dex/requirements.yaml
  stable/dex/templates/deployment.yaml
  stable/dex/templates/job-grpc-certs.yaml
  stable/dex/templates/job-web-certs.yaml
  stable/dex/values.yaml
Labels: ready, ok-to-test

#1417 feat: Add priorityClassName to knative manifests
  staging/knative/charts/serving/templates/net-istio.yaml
  staging/knative/charts/serving/templates/pre-upgrade-hook.yaml
  staging/knative/charts/serving/templates/serving-core.yaml
  staging/knative/charts/serving/templates/serving-hpa.yaml
  staging/knative/values.yaml
Labels: ready, ok-to-test, stacked

#1406 feat: Upgrade knative to latest knative-serving
  stable/cert-manager-setup/Chart.yaml
  stable/cert-manager-setup/charts/cert-manager-v1.0.3.tgz
  stable/cert-manager-setup/charts/cert-manager-v1.11.0.tgz
  stable/cert-manager-setup/requirements.lock
  stable/cert-manager-setup/requirements.yaml
  staging/knative/Chart.yaml
  staging/knative/PATCHES.md
  staging/knative/README.md
  staging/knative/charts/eventing-sources/Chart.yaml
  staging/knative/charts/eventing-sources/charts/github/Chart.yaml
  staging/knative/charts/eventing-sources/charts/github/templates/github.yaml
  staging/knative/charts/eventing/Chart.yaml
  staging/knative/charts/eventing/templates/eventing.yaml
  staging/knative/charts/serving/Chart.yaml
  staging/knative/charts/serving/crds/serving-crds.yaml
  staging/knative/charts/serving/templates/_helpers.tpl
  staging/knative/charts/serving/templates/net-istio.yaml
  staging/knative/charts/serving/templates/pre-upgrade-hook.yaml
  staging/knative/charts/serving/templates/serving-core.yaml
  staging/knative/charts/serving/templates/serving-hpa.yaml
  staging/knative/values.yaml
  test/e2e-kind.sh
Labels: ready, dependencies, ok-to-test

#1418 feat: Bump kubecost to 1.102.2
  stable/kubecost/Chart.lock
  stable/kubecost/Chart.yaml
  stable/kubecost/charts/cost-analyzer-1.100.2.tgz
  stable/kubecost/charts/cost-analyzer-1.102.2.tgz
Labels: ready, ok-to-test
