Repository mesosphere/charts, pull requests merged in 2024-02, with the labels that each got.

#1480 ci: remove mergebot
  .github/workflows/mergebot.yml
  mergebot-config.json
Labels: ready, ok-to-test

#1481 fix: use GITHUB_TOKEN to publish charts
  .github/workflows/publish.yml
Labels: bug, ready

#1484 feat(kps): Bump to 56.8.0
  staging/kube-prometheus-stack/Chart.lock
  staging/kube-prometheus-stack/Chart.yaml
  staging/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
  staging/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
  staging/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
  staging/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
  staging/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
  staging/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
  staging/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
  staging/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
  staging/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
  staging/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml
  staging/kube-prometheus-stack/templates/_helpers.tpl
  staging/kube-prometheus-stack/templates/alertmanager/ingress.yaml
  staging/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml
  staging/kube-prometheus-stack/templates/grafana/dashboards-1.14/prometheus.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/deployment.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/pdb.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/deployment/service.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/ciliumnetworkpolicy.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/clusterrole.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/clusterrolebinding.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/networkpolicy.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/psp-clusterrole.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/psp-clusterrolebinding.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/psp.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/service.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml
  staging/kube-prometheus-stack/templates/prometheus-operator/verticalpodautoscaler.yaml
  staging/kube-prometheus-stack/templates/prometheus/ingress.yaml
  staging/kube-prometheus-stack/templates/prometheus/ingressThanosSidecar.yaml
  staging/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml
  staging/kube-prometheus-stack/templates/prometheus/prometheus.yaml
  staging/kube-prometheus-stack/templates/thanos-ruler/ingress.yaml
  staging/kube-prometheus-stack/upgrade_operator.sh
  staging/kube-prometheus-stack/values.yaml
Labels: ready

#1482 feat(kubecost): Bump chart to 1.106.7
  stable/kubecost/Chart.lock
  stable/kubecost/Chart.yaml
  stable/kubecost/README.md
  stable/kubecost/charts/cost-analyzer-1.106.5.tgz
  stable/kubecost/charts/cost-analyzer-1.106.7.tgz
  stable/kubecost/values.yaml
Labels: ready

#1483 feat(istio): Bump to upstream 1.20.3
  staging/istio/.helmignore
  staging/istio/Chart.yaml
  staging/istio/patch/patches/1_values.patch
  staging/istio/upgrade_operator.sh
  staging/istio/values.yaml
Labels: ready

#1485 feat(knative/dex/cert-federation/obc): Bump kubectl to 1.29.2
  stable/dex/Chart.yaml
  stable/dex/values.yaml
  stable/kommander-cert-federation/Chart.yaml
  stable/kommander-cert-federation/values.yaml
  stable/object-bucket-claim/Chart.yaml
  stable/object-bucket-claim/templates/object-bucket-claim.yaml
  stable/object-bucket-claim/values.yaml
  staging/knative/Chart.yaml
  staging/knative/charts/serving/Chart.yaml
  staging/knative/charts/serving/values.yaml
Labels: ready

#1486 chore(dex): bump dex-controller to v0.14.1
  stable/dex/Chart.yaml
  stable/dex/charts/dex-controller-v0.14.0.tgz
  stable/dex/charts/dex-controller-v0.14.1.tgz
  stable/dex/requirements.lock
  stable/dex/requirements.yaml
Labels: ready, ok-to-test

#1487 fix(obc): Use root scope for values
  stable/object-bucket-claim/Chart.yaml
  stable/object-bucket-claim/templates/object-bucket-claim.yaml
Labels: ready, ok-to-test

#1488 feat(kps): Upgrade to 56.9.0
  staging/kube-prometheus-stack/Chart.lock
  staging/kube-prometheus-stack/Chart.yaml
  staging/kube-prometheus-stack/ci/03-non-defaults-values.yaml
  staging/kube-prometheus-stack/hack/sync_prometheus_rules.py
  staging/kube-prometheus-stack/patch/mesosphere/templates/hooks/pre-upgrade-del-ksm-deploy.yaml
  staging/kube-prometheus-stack/patch/mesosphere/templates/rules/mesosphere-rules/elasticsearch-rules.yaml
  staging/kube-prometheus-stack/patch/patch_6_mesosphere_values.sh
  staging/kube-prometheus-stack/templates/alertmanager/ingressperreplica.yaml
  staging/kube-prometheus-stack/templates/mesosphere-hooks/pre-upgrade-del-ksm-deploy.yaml
  staging/kube-prometheus-stack/templates/prometheus/ingressperreplica.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/alertmanager.rules.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/config-reloaders.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/etcd.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/general.rules.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver-slos.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-state-metrics.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-resources.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-storage.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kube-proxy.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system-scheduler.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-system.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/node-network.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus-operator.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus.yaml
  staging/kube-prometheus-stack/templates/prometheus/rules/mesosphere-rules/elasticsearch-rules.yaml
  staging/kube-prometheus-stack/upgrade_operator.sh
  staging/kube-prometheus-stack/values.yaml
Labels: ready, ok-to-test

#1490 feat(cert-manager): Update to 1.14.2
  stable/cert-manager-crds/Chart.yaml
  stable/cert-manager-crds/Makefile
  stable/cert-manager-crds/crds/cert-manager.crds.yaml
Labels: ready, ok-to-test

#1494 fix(kommander-cert-federation): fix command definition
  stable/kommander-cert-federation/Chart.yaml
  stable/kommander-cert-federation/templates/cert-federation.yaml
Labels: ready, ok-to-test
